#!/bin/sh
set -eu

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

safe_abs_path() {
  name="$1"
  value="$2"

  [ -n "$value" ] || fail "$name is empty"
  case "$value" in
    /*) ;;
    *) fail "$name must be an absolute path: $value" ;;
  esac
  case "$value" in
    "/"|"/opt"|"/home"|"/home/deploy"|"/tmp"|"/var"|"/usr"|"/etc")
      fail "$name is too broad: $value"
      ;;
  esac
  case "$value" in
    *".."*|*" "*|*"'"*|*'"'*|*";"*|*"|"*|*"&"*|*'$'*|*"("*|*")"*|*"["*|*"]"*|*"{"*|*"}"*|*"!"*|*"*"*|*"?"*)
      fail "$name contains unsafe characters: $value"
      ;;
  esac
}

safe_token() {
  name="$1"
  value="$2"

  [ -n "$value" ] || fail "$name is empty"
  case "$value" in
    *"'"*|*'"'*|*";"*|*"|"*|*"&"*|*'`'*|*'$'*|*"("*|*")"*|*"!"*)
      fail "$name contains unsafe characters"
      ;;
  esac
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || fail "missing required command: $1"
}

env_value_or_default() {
  name="$1"
  default="$2"
  eval "value=\${$name:-}"
  if [ -n "$value" ]; then
    printf '%s' "$value"
  else
    printf '%s' "$default"
  fi
}

required_env_value() {
  name="$1"
  eval "value=\${$name:-}"
  [ -n "$value" ] || fail "$name is required"
  printf '%s' "$value"
}

write_env_line() {
  file="$1"
  name="$2"
  value="$3"

  case "$value" in
    *"
"*) fail "$name must not contain newlines" ;;
  esac
  printf '%s=%s\n' "$name" "$value" >> "$file"
}

generate_production_env_file() {
  file="$(mktemp)"
  {
    printf '%s\n' "# Generated by GitLab CI. Do not edit on server."
    printf '%s\n' "# Commit: ${CI_COMMIT_SHA:-local}"
  } > "$file"

  write_env_line "$file" ARGUS_PUBLIC_URL "$(env_value_or_default ARGUS_PUBLIC_URL "https://argusai.kz")"
  write_env_line "$file" ARGUS_CORS_ORIGINS "$(env_value_or_default ARGUS_CORS_ORIGINS "https://argusai.kz,https://www.argusai.kz")"
  write_env_line "$file" WEBIZON_PUBLIC_URL "$(env_value_or_default WEBIZON_PUBLIC_URL "https://webizon.kz")"
  write_env_line "$file" CERTBOT_EMAIL "$(required_env_value CERTBOT_EMAIL)"

  write_env_line "$file" ARGUS_FRONTEND_IMAGE "$(env_value_or_default ARGUS_FRONTEND_IMAGE "registry.gitlab.com/argus_ai_group/argus-frontend:latest")"
  write_env_line "$file" ARGUS_BACKEND_IMAGE "$(env_value_or_default ARGUS_BACKEND_IMAGE "registry.gitlab.com/argus_ai_group/argus-backend:latest")"
  write_env_line "$file" ARGUS_WORKER_IMAGE "$(env_value_or_default ARGUS_WORKER_IMAGE "registry.gitlab.com/argus_ai_group/argus-backend/worker:latest")"
  write_env_line "$file" ARGUS_INFERENCE_IMAGE "$(env_value_or_default ARGUS_INFERENCE_IMAGE "registry.gitlab.com/argus_ai_group/argus-backend/inference:latest")"
  write_env_line "$file" ARGUS_AI_SIDECAR_IMAGE "$(env_value_or_default ARGUS_AI_SIDECAR_IMAGE "registry.gitlab.com/argus_ai_group/argus-backend/ai-sidecar:latest")"
  write_env_line "$file" WEBIZON_APP_IMAGE "$(required_env_value WEBIZON_APP_IMAGE)"

  write_env_line "$file" ARGUS_JWT_SIGNING_KEY "$(required_env_value ARGUS_JWT_SIGNING_KEY)"
  write_env_line "$file" ARGUS_POSTGRES_DB "$(env_value_or_default ARGUS_POSTGRES_DB "argus_db")"
  write_env_line "$file" ARGUS_POSTGRES_USER "$(env_value_or_default ARGUS_POSTGRES_USER "argus")"
  write_env_line "$file" ARGUS_POSTGRES_PASSWORD "$(required_env_value ARGUS_POSTGRES_PASSWORD)"
  write_env_line "$file" ARGUS_CLICKHOUSE_DATABASE "$(env_value_or_default ARGUS_CLICKHOUSE_DATABASE "argus_analytics")"
  write_env_line "$file" ARGUS_CLICKHOUSE_USER "$(env_value_or_default ARGUS_CLICKHOUSE_USER "default")"
  write_env_line "$file" ARGUS_CLICKHOUSE_PASSWORD "$(required_env_value ARGUS_CLICKHOUSE_PASSWORD)"
  write_env_line "$file" ARGUS_MINIO_ROOT_USER "$(env_value_or_default ARGUS_MINIO_ROOT_USER "argus-minio-admin")"
  write_env_line "$file" ARGUS_MINIO_ROOT_PASSWORD "$(required_env_value ARGUS_MINIO_ROOT_PASSWORD)"
  write_env_line "$file" ARGUS_MINIO_BUCKET "$(env_value_or_default ARGUS_MINIO_BUCKET "argus-evidence")"
  write_env_line "$file" ARGUS_MINIO_EXPORT_BUCKET "$(env_value_or_default ARGUS_MINIO_EXPORT_BUCKET "argus-exports")"

  write_env_line "$file" ARGUS_MODELS_PATH "$(env_value_or_default ARGUS_MODELS_PATH "$ARGUS_PROJECT_ROOT/argus-backend/models")"
  write_env_line "$file" ARGUS_YOLO_MODEL_FILE "$(env_value_or_default ARGUS_YOLO_MODEL_FILE "yolov8n.onnx")"
  write_env_line "$file" ARGUS_ARCFACE_MODEL_FILE "$(env_value_or_default ARGUS_ARCFACE_MODEL_FILE "arcface.onnx")"
  write_env_line "$file" ARGUS_YOLO_CONFIDENCE_THRESHOLD "$(env_value_or_default ARGUS_YOLO_CONFIDENCE_THRESHOLD "0.35")"
  write_env_line "$file" ARGUS_FACE_MISMATCH_THRESHOLD "$(env_value_or_default ARGUS_FACE_MISMATCH_THRESHOLD "0.62")"
  write_env_line "$file" ARGUS_AUDIO_VAD_THRESHOLD "$(env_value_or_default ARGUS_AUDIO_VAD_THRESHOLD "0.65")"
  write_env_line "$file" ARGUS_FRAME_EXTRACTION_INTERVAL_SEC "$(env_value_or_default ARGUS_FRAME_EXTRACTION_INTERVAL_SEC "4")"
  write_env_line "$file" ARGUS_LOG_LEVEL "$(env_value_or_default ARGUS_LOG_LEVEL "info")"

  write_env_line "$file" WEBIZON_POSTGRES_DB "$(env_value_or_default WEBIZON_POSTGRES_DB "webizon")"
  write_env_line "$file" WEBIZON_POSTGRES_USER "$(env_value_or_default WEBIZON_POSTGRES_USER "webizon")"
  write_env_line "$file" WEBIZON_POSTGRES_PASSWORD "$(required_env_value WEBIZON_POSTGRES_PASSWORD)"

  chmod 600 "$file"
  printf '%s\n' "$file"
}

materialize_ssh_key() {
  raw_key="${ARGUS_DEPLOY_SSH_KEY:-${DEPLOY_SSH_KEY:-${SSH_PRIVATE_KEY:-}}}"
  [ -n "$raw_key" ] || fail "SSH key is required. Set DEPLOY_SSH_KEY, ARGUS_DEPLOY_SSH_KEY, or SSH_PRIVATE_KEY"

  if [ -r "$raw_key" ]; then
    printf '%s\n' "$raw_key"
    return 0
  fi

  key_file="$(mktemp)"
  case "$raw_key" in
    *"\\n"*) printf '%b' "$raw_key" ;;
    *) printf '%s\n' "$raw_key" ;;
  esac | sed 's/\r$//' > "$key_file"
  chmod 600 "$key_file"
  printf '%s\n' "$key_file"
}

ARGUS_DEPLOY_HOST="${ARGUS_DEPLOY_HOST:-${DEPLOY_HOST:-}}"
ARGUS_DEPLOY_USER="${ARGUS_DEPLOY_USER:-${DEPLOY_USER:-deploy}}"
ARGUS_PROJECT_ROOT="${ARGUS_PROJECT_ROOT:-${DEPLOY_PATH:-/opt/argus-ai}}"
ARGUS_INFRA_DEPLOY_PATH="${ARGUS_INFRA_DEPLOY_PATH:-$ARGUS_PROJECT_ROOT/argus-infra}"
REGISTRY_HOST="${REGISTRY_HOST:-${CI_REGISTRY:-registry.gitlab.com}}"
REGISTRY_USER_VALUE="${REGISTRY_USER:-${CI_REGISTRY_USER:-}}"
REGISTRY_PASSWORD_VALUE="${REGISTRY_PASSWORD:-${CI_REGISTRY_PASSWORD:-}}"
ARGUS_SYNC_PROD_ENV="${ARGUS_SYNC_PROD_ENV:-true}"

[ -n "$ARGUS_DEPLOY_HOST" ] || fail "DEPLOY_HOST or ARGUS_DEPLOY_HOST is required"
[ -n "$ARGUS_DEPLOY_USER" ] || fail "DEPLOY_USER or ARGUS_DEPLOY_USER is required"
[ -n "$REGISTRY_USER_VALUE" ] || fail "REGISTRY_USER or CI_REGISTRY_USER is required"
[ -n "$REGISTRY_PASSWORD_VALUE" ] || fail "REGISTRY_PASSWORD or CI_REGISTRY_PASSWORD is required"

safe_abs_path "ARGUS_PROJECT_ROOT" "$ARGUS_PROJECT_ROOT"
safe_abs_path "ARGUS_INFRA_DEPLOY_PATH" "$ARGUS_INFRA_DEPLOY_PATH"
safe_token "REGISTRY_HOST" "$REGISTRY_HOST"
safe_token "REGISTRY_USER" "$REGISTRY_USER_VALUE"

require_cmd ssh
require_cmd ssh-agent
require_cmd ssh-add
require_cmd ssh-keygen
require_cmd ssh-keyscan
require_cmd rsync

SSH_KEY_FILE="$(materialize_ssh_key)"
PROD_ENV_FILE=""
REMOVE_SSH_KEY_FILE="false"
if [ -r "$SSH_KEY_FILE" ] && [ "${SSH_KEY_FILE#/tmp/}" != "$SSH_KEY_FILE" ]; then
  REMOVE_SSH_KEY_FILE="true"
fi
if [ "$ARGUS_SYNC_PROD_ENV" = "true" ]; then
  PROD_ENV_FILE="$(generate_production_env_file)"
fi

eval "$(ssh-agent -s)"
trap 'ssh-agent -k >/dev/null 2>&1 || true; if [ "${REMOVE_SSH_KEY_FILE:-false}" = "true" ]; then rm -f "${SSH_KEY_FILE:-}" 2>/dev/null || true; fi; rm -f "${PROD_ENV_FILE:-}" 2>/dev/null || true' EXIT

chmod 600 "$SSH_KEY_FILE"
ssh-keygen -lf "$SSH_KEY_FILE"
ssh-add "$SSH_KEY_FILE"
mkdir -p "$HOME/.ssh"
chmod 700 "$HOME/.ssh"
ssh-keyscan -H "$ARGUS_DEPLOY_HOST" >> "$HOME/.ssh/known_hosts" 2>/dev/null

SSH_TARGET="$ARGUS_DEPLOY_USER@$ARGUS_DEPLOY_HOST"

echo "Checking SSH access to $SSH_TARGET..."
ssh -o BatchMode=yes -o StrictHostKeyChecking=yes "$SSH_TARGET" "printf '%s\n' ssh-ok"

echo "============================================================"
echo "Syncing Argus+Webizon production stack to $ARGUS_DEPLOY_HOST"
echo "Path: $ARGUS_INFRA_DEPLOY_PATH"
echo "Commit: ${CI_COMMIT_SHORT_SHA:-local}"
echo "============================================================"

ssh "$SSH_TARGET" "mkdir -p '$ARGUS_INFRA_DEPLOY_PATH/docker' '$ARGUS_INFRA_DEPLOY_PATH/nginx' '$ARGUS_INFRA_DEPLOY_PATH/migrations' '$ARGUS_INFRA_DEPLOY_PATH/scripts' '$ARGUS_PROJECT_ROOT/argus-backend/models'"

rsync -azO \
  docker/docker-compose.argus-webizon.prod.yml \
  docker/.env.argus-webizon.example \
  docker/config.yaml \
  "$SSH_TARGET:$ARGUS_INFRA_DEPLOY_PATH/docker/"

if [ "$ARGUS_SYNC_PROD_ENV" = "true" ]; then
  rsync -azO "$PROD_ENV_FILE" "$SSH_TARGET:$ARGUS_INFRA_DEPLOY_PATH/docker/.env"
fi

rsync -azO \
  nginx/nginx.argus-webizon.conf \
  "$SSH_TARGET:$ARGUS_INFRA_DEPLOY_PATH/nginx/"

rsync -azO \
  migrations/ \
  "$SSH_TARGET:$ARGUS_INFRA_DEPLOY_PATH/migrations/"

rsync -azO \
  scripts/ \
  "$SSH_TARGET:$ARGUS_INFRA_DEPLOY_PATH/scripts/"

ssh "$SSH_TARGET" "chmod +x '$ARGUS_INFRA_DEPLOY_PATH'/scripts/*.sh 2>/dev/null || true"

echo "Logging Docker into $REGISTRY_HOST on the server..."
printf '%s\n' "$REGISTRY_PASSWORD_VALUE" | ssh "$SSH_TARGET" "docker login '$REGISTRY_HOST' -u '$REGISTRY_USER_VALUE' --password-stdin >/dev/null"

echo "Running remote deployment preflight and compose up..."
ssh "$SSH_TARGET" \
  "ARGUS_PROJECT_ROOT='$ARGUS_PROJECT_ROOT' ARGUS_INFRA_DEPLOY_PATH='$ARGUS_INFRA_DEPLOY_PATH' ARGUS_CLEAN_OLD_CONTAINERS='${ARGUS_CLEAN_OLD_CONTAINERS:-false}' ARGUS_BOOTSTRAP_CERTS='${ARGUS_BOOTSTRAP_CERTS:-true}' sh -s" <<'REMOTE_SCRIPT'
set -eu

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

compose() {
  if docker compose version >/dev/null 2>&1; then
    docker compose "$@"
  elif command -v docker-compose >/dev/null 2>&1; then
    docker-compose "$@"
  else
    fail "docker compose is not installed"
  fi
}

env_value() {
  key="$1"
  awk -v key="$key" 'index($0, key "=") == 1 { print substr($0, length(key) + 2); exit }' .env
}

have_cert() {
  domain="$1"
  docker run --rm -v prod_letsencrypt:/etc/letsencrypt alpine:3.20 \
    sh -c "test -s '/etc/letsencrypt/live/$domain/fullchain.pem' && test -s '/etc/letsencrypt/live/$domain/privkey.pem'" >/dev/null 2>&1
}

issue_cert_if_missing() {
  primary="$1"
  shift

  if have_cert "$primary"; then
    echo "TLS certificate exists for $primary"
    return 0
  fi

  [ "$ARGUS_BOOTSTRAP_CERTS" = "true" ] || fail "TLS certificate for $primary is missing. Set ARGUS_BOOTSTRAP_CERTS=true for first run."
  [ -n "$certbot_email" ] || fail "CERTBOT_EMAIL is required in docker/.env for first certificate issue"

  echo "Issuing Let's Encrypt certificate for $primary..."
  args=""
  for domain in "$primary" "$@"; do
    args="$args -d $domain"
  done
  # shellcheck disable=SC2086
  docker run --rm -p 80:80 \
    -v prod_letsencrypt:/etc/letsencrypt \
    -v prod_certbot_webroot:/var/www/certbot \
    certbot/certbot:v2.11.0 certonly --standalone --non-interactive --agree-tos --no-eff-email \
    --email "$certbot_email" $args
}

case "$ARGUS_INFRA_DEPLOY_PATH" in
  ""|"/"|"/opt"|"/home"|"/home/deploy"|"/tmp"|"/var"|"/usr"|"/etc")
    fail "unsafe ARGUS_INFRA_DEPLOY_PATH: $ARGUS_INFRA_DEPLOY_PATH"
    ;;
esac

cd "$ARGUS_INFRA_DEPLOY_PATH/docker"

if [ ! -f .env ]; then
  cp .env.argus-webizon.example .env
  fail "created docker/.env from example. Fill real secrets and registry image tags on the server, then rerun deploy."
fi

if grep -Eq '=(change-me|change-me-|.*change-in-production)' .env; then
  fail "docker/.env still contains placeholder values. Replace every change-me value before production deploy."
fi

models_path="$(env_value ARGUS_MODELS_PATH)"
[ -n "$models_path" ] || models_path="$ARGUS_PROJECT_ROOT/argus-backend/models"
yolo_model="$(env_value ARGUS_YOLO_MODEL_FILE)"
[ -n "$yolo_model" ] || yolo_model="yolov8n.onnx"
arcface_model="$(env_value ARGUS_ARCFACE_MODEL_FILE)"
[ -n "$arcface_model" ] || arcface_model="arcface.onnx"
certbot_email="$(env_value CERTBOT_EMAIL)"

[ -s "$models_path/$yolo_model" ] || fail "missing YOLO model: $models_path/$yolo_model"
[ -s "$models_path/$arcface_model" ] || fail "missing ArcFace model: $models_path/$arcface_model"

docker volume create prod_letsencrypt >/dev/null
docker volume create prod_certbot_webroot >/dev/null

if [ "$ARGUS_CLEAN_OLD_CONTAINERS" = "true" ]; then
  echo "Removing old Argus/Webizon containers without deleting named volumes..."
  compose --env-file .env -f docker-compose.argus-webizon.prod.yml down --remove-orphans >/dev/null 2>&1 || true
  docker rm -f \
    argus-backend-app argus-frontend-app argus-inference argus-ai-sidecar \
    argus-clickhouse argus-redis argus-db argus-postgres argus-kafka \
    argus-zookeeper argus-worker argus-minio argus-minio-init \
    prod-nginx prod-certbot webizon-app webizon-postgres \
    >/dev/null 2>&1 || true
fi

issue_cert_if_missing argusai.kz www.argusai.kz
issue_cert_if_missing webizon.kz www.webizon.kz

compose --env-file .env -f docker-compose.argus-webizon.prod.yml config --quiet
compose --env-file .env -f docker-compose.argus-webizon.prod.yml pull
compose --env-file .env -f docker-compose.argus-webizon.prod.yml up -d --remove-orphans --wait

echo ""
echo "Container status:"
compose --env-file .env -f docker-compose.argus-webizon.prod.yml ps

echo ""
echo "Health checks:"
docker exec argus-backend wget -qO- http://127.0.0.1:8080/healthz >/dev/null
docker exec argus-ai-sidecar python3 -c "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8091/healthz')" >/dev/null
docker exec prod-nginx wget -qO- http://127.0.0.1/healthz >/dev/null
docker exec webizon-app sh -c "wget -qO- http://127.0.0.1:8080/actuator/health >/dev/null || wget -qO- http://127.0.0.1:8080/ >/dev/null"

echo "Argus+Webizon deployment completed."
REMOTE_SCRIPT

echo "============================================================"
echo "ARGUS+WEBIZON DEPLOY SUCCESS"
echo "============================================================"
