// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: api/proto/v1/event_collector.proto

package eventcollectorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventCollectorService_IngestEvent_FullMethodName  = "/argus.eventcollector.v1.EventCollectorService/IngestEvent"
	EventCollectorService_IngestBatch_FullMethodName  = "/argus.eventcollector.v1.EventCollectorService/IngestBatch"
	EventCollectorService_StreamEvents_FullMethodName = "/argus.eventcollector.v1.EventCollectorService/StreamEvents"
	EventCollectorService_Heartbeat_FullMethodName    = "/argus.eventcollector.v1.EventCollectorService/Heartbeat"
)

// EventCollectorServiceClient is the client API for EventCollectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventCollectorServiceClient interface {
	// IngestEvent accepts a single proctoring event from a browser client.
	// Used for critical, low-latency events (face mismatch, phone detected).
	IngestEvent(ctx context.Context, in *IngestEventRequest, opts ...grpc.CallOption) (*IngestEventResponse, error)
	// IngestBatch accepts a batch of events from a browser client.
	// Preferred path for high-frequency telemetry (gaze tracking, mouse moves).
	// Reduces gRPC overhead by amortizing connection cost across N events.
	IngestBatch(ctx context.Context, in *IngestBatchRequest, opts ...grpc.CallOption) (*IngestBatchResponse, error)
	// StreamEvents opens a bidirectional stream for continuous event ingestion.
	// Used by the browser extension for persistent, low-overhead telemetry.
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IngestEventRequest, StreamAck], error)
	// Heartbeat keeps the session alive and reports basic health.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type eventCollectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventCollectorServiceClient(cc grpc.ClientConnInterface) EventCollectorServiceClient {
	return &eventCollectorServiceClient{cc}
}

func (c *eventCollectorServiceClient) IngestEvent(ctx context.Context, in *IngestEventRequest, opts ...grpc.CallOption) (*IngestEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestEventResponse)
	err := c.cc.Invoke(ctx, EventCollectorService_IngestEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventCollectorServiceClient) IngestBatch(ctx context.Context, in *IngestBatchRequest, opts ...grpc.CallOption) (*IngestBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestBatchResponse)
	err := c.cc.Invoke(ctx, EventCollectorService_IngestBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventCollectorServiceClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IngestEventRequest, StreamAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventCollectorService_ServiceDesc.Streams[0], EventCollectorService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IngestEventRequest, StreamAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventCollectorService_StreamEventsClient = grpc.BidiStreamingClient[IngestEventRequest, StreamAck]

func (c *eventCollectorServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, EventCollectorService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventCollectorServiceServer is the server API for EventCollectorService service.
// All implementations must embed UnimplementedEventCollectorServiceServer
// for forward compatibility.
type EventCollectorServiceServer interface {
	// IngestEvent accepts a single proctoring event from a browser client.
	// Used for critical, low-latency events (face mismatch, phone detected).
	IngestEvent(context.Context, *IngestEventRequest) (*IngestEventResponse, error)
	// IngestBatch accepts a batch of events from a browser client.
	// Preferred path for high-frequency telemetry (gaze tracking, mouse moves).
	// Reduces gRPC overhead by amortizing connection cost across N events.
	IngestBatch(context.Context, *IngestBatchRequest) (*IngestBatchResponse, error)
	// StreamEvents opens a bidirectional stream for continuous event ingestion.
	// Used by the browser extension for persistent, low-overhead telemetry.
	StreamEvents(grpc.BidiStreamingServer[IngestEventRequest, StreamAck]) error
	// Heartbeat keeps the session alive and reports basic health.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedEventCollectorServiceServer()
}

// UnimplementedEventCollectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventCollectorServiceServer struct{}

func (UnimplementedEventCollectorServiceServer) IngestEvent(context.Context, *IngestEventRequest) (*IngestEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngestEvent not implemented")
}
func (UnimplementedEventCollectorServiceServer) IngestBatch(context.Context, *IngestBatchRequest) (*IngestBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngestBatch not implemented")
}
func (UnimplementedEventCollectorServiceServer) StreamEvents(grpc.BidiStreamingServer[IngestEventRequest, StreamAck]) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedEventCollectorServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedEventCollectorServiceServer) mustEmbedUnimplementedEventCollectorServiceServer() {}
func (UnimplementedEventCollectorServiceServer) testEmbeddedByValue()                               {}

// UnsafeEventCollectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventCollectorServiceServer will
// result in compilation errors.
type UnsafeEventCollectorServiceServer interface {
	mustEmbedUnimplementedEventCollectorServiceServer()
}

func RegisterEventCollectorServiceServer(s grpc.ServiceRegistrar, srv EventCollectorServiceServer) {
	// If the following call pancis, it indicates UnimplementedEventCollectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventCollectorService_ServiceDesc, srv)
}

func _EventCollectorService_IngestEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventCollectorServiceServer).IngestEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventCollectorService_IngestEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventCollectorServiceServer).IngestEvent(ctx, req.(*IngestEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventCollectorService_IngestBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventCollectorServiceServer).IngestBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventCollectorService_IngestBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventCollectorServiceServer).IngestBatch(ctx, req.(*IngestBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventCollectorService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventCollectorServiceServer).StreamEvents(&grpc.GenericServerStream[IngestEventRequest, StreamAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventCollectorService_StreamEventsServer = grpc.BidiStreamingServer[IngestEventRequest, StreamAck]

func _EventCollectorService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventCollectorServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventCollectorService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventCollectorServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventCollectorService_ServiceDesc is the grpc.ServiceDesc for EventCollectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventCollectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "argus.eventcollector.v1.EventCollectorService",
	HandlerType: (*EventCollectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngestEvent",
			Handler:    _EventCollectorService_IngestEvent_Handler,
		},
		{
			MethodName: "IngestBatch",
			Handler:    _EventCollectorService_IngestBatch_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _EventCollectorService_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _EventCollectorService_StreamEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/v1/event_collector.proto",
}
