// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/v1/event_collector.proto

package eventcollectorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	// Video & Face events
	EventType_GAZE_DEVIATION            EventType = 1
	EventType_FACE_MISMATCH             EventType = 2
	EventType_FACE_NOT_DETECTED         EventType = 3
	EventType_FACE_SPOOF_DETECTED       EventType = 4
	EventType_MULTIPLE_PERSONS          EventType = 5
	EventType_DYNAMIC_FACE_RECHECK_FAIL EventType = 6
	// AI Vision events (biometric inference)
	EventType_HEAD_POSE_ANOMALY     EventType = 7 // Yaw/Pitch/Roll outside threshold
	EventType_LIVENESS_CHECK_FAILED EventType = 8 // Eye-blink + texture liveness failure
	EventType_FACE_OCCLUDED         EventType = 9 // Partial face occlusion detected
	// Object detection events
	EventType_PHONE_DETECTED          EventType = 10
	EventType_BOOK_DETECTED           EventType = 11
	EventType_EARBUDS_DETECTED        EventType = 12
	EventType_UNKNOWN_OBJECT_DETECTED EventType = 13
	// Audio events
	EventType_VOICE_ACTIVITY           EventType = 20
	EventType_AUDIO_ANOMALY            EventType = 21
	EventType_AUDIO_PERIPHERY_DETECTED EventType = 22
	EventType_SMART_NOISE_CLASSIFIED   EventType = 23
	// AI Audio events (sound activity detection)
	EventType_WHISPER_DETECTED        EventType = 24 // Low-amplitude speech (<40dB)
	EventType_SECOND_SPEAKER_DETECTED EventType = 25 // Voice embedding mismatch
	EventType_AUDIO_PLAYBACK_DETECTED EventType = 26 // TTS/recorded audio fingerprint
	// Browser events
	EventType_TAB_SWITCH                EventType = 30
	EventType_COPY_PASTE_ATTEMPT        EventType = 31
	EventType_PRINT_SCREEN_ATTEMPT      EventType = 32
	EventType_CONTEXT_MENU_ATTEMPT      EventType = 33
	EventType_FULLSCREEN_EXIT           EventType = 34
	EventType_EXTERNAL_DISPLAY_DETECTED EventType = 35
	// Network events
	EventType_VPN_PROXY_DETECTED        EventType = 40
	EventType_SUSPICIOUS_NETWORK_DEVICE EventType = 41
	// Psychometry events
	EventType_EMOTION_STRESS_SPIKE  EventType = 50
	EventType_FOCUS_LOSS_DETECTED   EventType = 51
	EventType_BLINK_PATTERN_ANOMALY EventType = 52
	// Kernel-level events
	EventType_TYPING_DYNAMICS_ANOMALY    EventType = 60
	EventType_HAND_CURSOR_DESYNC         EventType = 61
	EventType_FORBIDDEN_PROCESS_DETECTED EventType = 62
	EventType_HARDWARE_DEVICE_ANOMALY    EventType = 63
	EventType_REMOTE_ACCESS_DETECTED     EventType = 64
	EventType_HARDWARE_ID_MISMATCH       EventType = 65
	EventType_VIRTUAL_MONITOR_DETECTED   EventType = 66
	EventType_VIRTUAL_MACHINE_DETECTED   EventType = 67
	// Secondary Camera events
	EventType_SIDECAM_DEVICE_DISPLACED    EventType = 70
	EventType_SIDECAM_HANDS_OFF_DESK      EventType = 71
	EventType_SIDECAM_BATTERY_CRITICAL    EventType = 72
	EventType_SIDECAM_STREAM_DISCONNECTED EventType = 73
	EventType_SIDECAM_CALIBRATION_FAILED  EventType = 74
	EventType_SIDECAM_THERMAL_THROTTLE    EventType = 75
	// Backend AI deep scan events (post-session GPU re-analysis)
	EventType_BACKEND_AI_FACE_MISMATCH     EventType = 80 // Backend confirmed face doesn't match enrolled
	EventType_BACKEND_AI_SCREEN_REFLECTION EventType = 81 // Another person's reflection detected on screen
	EventType_BACKEND_AI_MICRO_EXPRESSION  EventType = 82 // Micro-expression indicating deception
	EventType_BACKEND_AI_HIDDEN_OBJECT     EventType = 83 // Object detected that frontend missed
	EventType_BACKEND_AI_DEEPFAKE_DETECTED EventType = 84 // Advanced deepfake analysis (backend-only model)
	EventType_BACKEND_AI_VOICE_SYNTH       EventType = 85 // Voice synthesis / TTS detected
	// Telemetry (high frequency, low severity)
	EventType_GAZE_TELEMETRY     EventType = 100
	EventType_MOUSE_TELEMETRY    EventType = 101
	EventType_KEYBOARD_TELEMETRY EventType = 102
	EventType_FOCUS_SCORE_UPDATE EventType = 103
	// AI Telemetry (continuous inference streams)
	EventType_HEAD_POSE_TELEMETRY      EventType = 104 // Continuous yaw/pitch/roll
	EventType_FACE_EMBEDDING_TELEMETRY EventType = 105 // Periodic face embedding snapshot
	EventType_AUDIO_LEVEL_TELEMETRY    EventType = 106 // Continuous dB + VAD stream
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:   "EVENT_TYPE_UNSPECIFIED",
		1:   "GAZE_DEVIATION",
		2:   "FACE_MISMATCH",
		3:   "FACE_NOT_DETECTED",
		4:   "FACE_SPOOF_DETECTED",
		5:   "MULTIPLE_PERSONS",
		6:   "DYNAMIC_FACE_RECHECK_FAIL",
		7:   "HEAD_POSE_ANOMALY",
		8:   "LIVENESS_CHECK_FAILED",
		9:   "FACE_OCCLUDED",
		10:  "PHONE_DETECTED",
		11:  "BOOK_DETECTED",
		12:  "EARBUDS_DETECTED",
		13:  "UNKNOWN_OBJECT_DETECTED",
		20:  "VOICE_ACTIVITY",
		21:  "AUDIO_ANOMALY",
		22:  "AUDIO_PERIPHERY_DETECTED",
		23:  "SMART_NOISE_CLASSIFIED",
		24:  "WHISPER_DETECTED",
		25:  "SECOND_SPEAKER_DETECTED",
		26:  "AUDIO_PLAYBACK_DETECTED",
		30:  "TAB_SWITCH",
		31:  "COPY_PASTE_ATTEMPT",
		32:  "PRINT_SCREEN_ATTEMPT",
		33:  "CONTEXT_MENU_ATTEMPT",
		34:  "FULLSCREEN_EXIT",
		35:  "EXTERNAL_DISPLAY_DETECTED",
		40:  "VPN_PROXY_DETECTED",
		41:  "SUSPICIOUS_NETWORK_DEVICE",
		50:  "EMOTION_STRESS_SPIKE",
		51:  "FOCUS_LOSS_DETECTED",
		52:  "BLINK_PATTERN_ANOMALY",
		60:  "TYPING_DYNAMICS_ANOMALY",
		61:  "HAND_CURSOR_DESYNC",
		62:  "FORBIDDEN_PROCESS_DETECTED",
		63:  "HARDWARE_DEVICE_ANOMALY",
		64:  "REMOTE_ACCESS_DETECTED",
		65:  "HARDWARE_ID_MISMATCH",
		66:  "VIRTUAL_MONITOR_DETECTED",
		67:  "VIRTUAL_MACHINE_DETECTED",
		70:  "SIDECAM_DEVICE_DISPLACED",
		71:  "SIDECAM_HANDS_OFF_DESK",
		72:  "SIDECAM_BATTERY_CRITICAL",
		73:  "SIDECAM_STREAM_DISCONNECTED",
		74:  "SIDECAM_CALIBRATION_FAILED",
		75:  "SIDECAM_THERMAL_THROTTLE",
		80:  "BACKEND_AI_FACE_MISMATCH",
		81:  "BACKEND_AI_SCREEN_REFLECTION",
		82:  "BACKEND_AI_MICRO_EXPRESSION",
		83:  "BACKEND_AI_HIDDEN_OBJECT",
		84:  "BACKEND_AI_DEEPFAKE_DETECTED",
		85:  "BACKEND_AI_VOICE_SYNTH",
		100: "GAZE_TELEMETRY",
		101: "MOUSE_TELEMETRY",
		102: "KEYBOARD_TELEMETRY",
		103: "FOCUS_SCORE_UPDATE",
		104: "HEAD_POSE_TELEMETRY",
		105: "FACE_EMBEDDING_TELEMETRY",
		106: "AUDIO_LEVEL_TELEMETRY",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":       0,
		"GAZE_DEVIATION":               1,
		"FACE_MISMATCH":                2,
		"FACE_NOT_DETECTED":            3,
		"FACE_SPOOF_DETECTED":          4,
		"MULTIPLE_PERSONS":             5,
		"DYNAMIC_FACE_RECHECK_FAIL":    6,
		"HEAD_POSE_ANOMALY":            7,
		"LIVENESS_CHECK_FAILED":        8,
		"FACE_OCCLUDED":                9,
		"PHONE_DETECTED":               10,
		"BOOK_DETECTED":                11,
		"EARBUDS_DETECTED":             12,
		"UNKNOWN_OBJECT_DETECTED":      13,
		"VOICE_ACTIVITY":               20,
		"AUDIO_ANOMALY":                21,
		"AUDIO_PERIPHERY_DETECTED":     22,
		"SMART_NOISE_CLASSIFIED":       23,
		"WHISPER_DETECTED":             24,
		"SECOND_SPEAKER_DETECTED":      25,
		"AUDIO_PLAYBACK_DETECTED":      26,
		"TAB_SWITCH":                   30,
		"COPY_PASTE_ATTEMPT":           31,
		"PRINT_SCREEN_ATTEMPT":         32,
		"CONTEXT_MENU_ATTEMPT":         33,
		"FULLSCREEN_EXIT":              34,
		"EXTERNAL_DISPLAY_DETECTED":    35,
		"VPN_PROXY_DETECTED":           40,
		"SUSPICIOUS_NETWORK_DEVICE":    41,
		"EMOTION_STRESS_SPIKE":         50,
		"FOCUS_LOSS_DETECTED":          51,
		"BLINK_PATTERN_ANOMALY":        52,
		"TYPING_DYNAMICS_ANOMALY":      60,
		"HAND_CURSOR_DESYNC":           61,
		"FORBIDDEN_PROCESS_DETECTED":   62,
		"HARDWARE_DEVICE_ANOMALY":      63,
		"REMOTE_ACCESS_DETECTED":       64,
		"HARDWARE_ID_MISMATCH":         65,
		"VIRTUAL_MONITOR_DETECTED":     66,
		"VIRTUAL_MACHINE_DETECTED":     67,
		"SIDECAM_DEVICE_DISPLACED":     70,
		"SIDECAM_HANDS_OFF_DESK":       71,
		"SIDECAM_BATTERY_CRITICAL":     72,
		"SIDECAM_STREAM_DISCONNECTED":  73,
		"SIDECAM_CALIBRATION_FAILED":   74,
		"SIDECAM_THERMAL_THROTTLE":     75,
		"BACKEND_AI_FACE_MISMATCH":     80,
		"BACKEND_AI_SCREEN_REFLECTION": 81,
		"BACKEND_AI_MICRO_EXPRESSION":  82,
		"BACKEND_AI_HIDDEN_OBJECT":     83,
		"BACKEND_AI_DEEPFAKE_DETECTED": 84,
		"BACKEND_AI_VOICE_SYNTH":       85,
		"GAZE_TELEMETRY":               100,
		"MOUSE_TELEMETRY":              101,
		"KEYBOARD_TELEMETRY":           102,
		"FOCUS_SCORE_UPDATE":           103,
		"HEAD_POSE_TELEMETRY":          104,
		"FACE_EMBEDDING_TELEMETRY":     105,
		"AUDIO_LEVEL_TELEMETRY":        106,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_event_collector_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_api_proto_v1_event_collector_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{0}
}

type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_INFO                 Severity = 1
	Severity_WARNING              Severity = 2
	Severity_CRITICAL             Severity = 3
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "INFO",
		2: "WARNING",
		3: "CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"INFO":                 1,
		"WARNING":              2,
		"CRITICAL":             3,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_event_collector_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_api_proto_v1_event_collector_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{1}
}

type EventSource int32

const (
	EventSource_SOURCE_UNSPECIFIED EventSource = 0
	EventSource_WEBCAM             EventSource = 1
	EventSource_SIDE_CAMERA        EventSource = 2
	EventSource_SYSTEM             EventSource = 3
	EventSource_BROWSER            EventSource = 4
	EventSource_KERNEL_AGENT       EventSource = 5
	EventSource_NETWORK_PROBE      EventSource = 6
	EventSource_BACKEND_AI         EventSource = 7 // Backend GPU-accelerated AI inference service
)

// Enum value maps for EventSource.
var (
	EventSource_name = map[int32]string{
		0: "SOURCE_UNSPECIFIED",
		1: "WEBCAM",
		2: "SIDE_CAMERA",
		3: "SYSTEM",
		4: "BROWSER",
		5: "KERNEL_AGENT",
		6: "NETWORK_PROBE",
		7: "BACKEND_AI",
	}
	EventSource_value = map[string]int32{
		"SOURCE_UNSPECIFIED": 0,
		"WEBCAM":             1,
		"SIDE_CAMERA":        2,
		"SYSTEM":             3,
		"BROWSER":            4,
		"KERNEL_AGENT":       5,
		"NETWORK_PROBE":      6,
		"BACKEND_AI":         7,
	}
)

func (x EventSource) Enum() *EventSource {
	p := new(EventSource)
	*p = x
	return p
}

func (x EventSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventSource) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_event_collector_proto_enumTypes[2].Descriptor()
}

func (EventSource) Type() protoreflect.EnumType {
	return &file_api_proto_v1_event_collector_proto_enumTypes[2]
}

func (x EventSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventSource.Descriptor instead.
func (EventSource) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{2}
}

type TelemetryMode int32

const (
	TelemetryMode_TELEMETRY_NORMAL    TelemetryMode = 0
	TelemetryMode_TELEMETRY_HIGH_FREQ TelemetryMode = 1 // Increase sampling (suspicious activity detected)
	TelemetryMode_TELEMETRY_LOW_FREQ  TelemetryMode = 2 // Decrease sampling (save bandwidth)
)

// Enum value maps for TelemetryMode.
var (
	TelemetryMode_name = map[int32]string{
		0: "TELEMETRY_NORMAL",
		1: "TELEMETRY_HIGH_FREQ",
		2: "TELEMETRY_LOW_FREQ",
	}
	TelemetryMode_value = map[string]int32{
		"TELEMETRY_NORMAL":    0,
		"TELEMETRY_HIGH_FREQ": 1,
		"TELEMETRY_LOW_FREQ":  2,
	}
)

func (x TelemetryMode) Enum() *TelemetryMode {
	p := new(TelemetryMode)
	*p = x
	return p
}

func (x TelemetryMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TelemetryMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_event_collector_proto_enumTypes[3].Descriptor()
}

func (TelemetryMode) Type() protoreflect.EnumType {
	return &file_api_proto_v1_event_collector_proto_enumTypes[3]
}

func (x TelemetryMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TelemetryMode.Descriptor instead.
func (TelemetryMode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{3}
}

type ProctoringEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique event identifier (UUIDv7 for time-ordered lexicographic sorting).
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Session identifier linking this event to an active proctoring session.
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Student identifier (IIN — Individual Identification Number).
	StudentId string `protobuf:"bytes,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	// Exam identifier from the ExamProctoringConfig.
	ExamId string `protobuf:"bytes,4,opt,name=exam_id,json=examId,proto3" json:"exam_id,omitempty"`
	// Organization/institution identifier for multi-tenant isolation.
	OrgId string `protobuf:"bytes,5,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Event classification.
	EventType EventType `protobuf:"varint,6,opt,name=event_type,json=eventType,proto3,enum=argus.eventcollector.v1.EventType" json:"event_type,omitempty"`
	// Severity classification for triage and alerting.
	Severity Severity `protobuf:"varint,7,opt,name=severity,proto3,enum=argus.eventcollector.v1.Severity" json:"severity,omitempty"`
	// Source camera/system that generated the event.
	Source EventSource `protobuf:"varint,8,opt,name=source,proto3,enum=argus.eventcollector.v1.EventSource" json:"source,omitempty"`
	// Server-side timestamp (set by the collector upon receipt).
	ServerTimestamp *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	// Client-side timestamp (set by the browser when event occurred).
	ClientTimestamp *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=client_timestamp,json=clientTimestamp,proto3" json:"client_timestamp,omitempty"`
	// Video timestamp in seconds from session start (for archive replay).
	VideoTimestampSec float64 `protobuf:"fixed64,11,opt,name=video_timestamp_sec,json=videoTimestampSec,proto3" json:"video_timestamp_sec,omitempty"`
	// Human-readable description of the event.
	Label string `protobuf:"bytes,12,opt,name=label,proto3" json:"label,omitempty"`
	// Confidence score from the AI model (0.0 - 1.0).
	Confidence float32 `protobuf:"fixed32,13,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Structured payload — type-specific data.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*ProctoringEvent_GazeDeviation
	//	*ProctoringEvent_FaceDetection
	//	*ProctoringEvent_ObjectDetection
	//	*ProctoringEvent_Audio
	//	*ProctoringEvent_Browser
	//	*ProctoringEvent_System
	//	*ProctoringEvent_Psychometry
	//	*ProctoringEvent_Network
	//	*ProctoringEvent_Kernel
	//	*ProctoringEvent_HeadPose
	//	*ProctoringEvent_Liveness
	//	*ProctoringEvent_AudioAnalysis
	//	*ProctoringEvent_FaceEmbedding
	Payload isProctoringEvent_Payload `protobuf_oneof:"payload"`
	// Client metadata for forensic analysis.
	ClientMeta    *ClientMeta `protobuf:"bytes,30,opt,name=client_meta,json=clientMeta,proto3" json:"client_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProctoringEvent) Reset() {
	*x = ProctoringEvent{}
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProctoringEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProctoringEvent) ProtoMessage() {}

func (x *ProctoringEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProctoringEvent.ProtoReflect.Descriptor instead.
func (*ProctoringEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{0}
}

func (x *ProctoringEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ProctoringEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProctoringEvent) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *ProctoringEvent) GetExamId() string {
	if x != nil {
		return x.ExamId
	}
	return ""
}

func (x *ProctoringEvent) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ProctoringEvent) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *ProctoringEvent) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *ProctoringEvent) GetSource() EventSource {
	if x != nil {
		return x.Source
	}
	return EventSource_SOURCE_UNSPECIFIED
}

func (x *ProctoringEvent) GetServerTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTimestamp
	}
	return nil
}

func (x *ProctoringEvent) GetClientTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ClientTimestamp
	}
	return nil
}

func (x *ProctoringEvent) GetVideoTimestampSec() float64 {
	if x != nil {
		return x.VideoTimestampSec
	}
	return 0
}

func (x *ProctoringEvent) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ProctoringEvent) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ProctoringEvent) GetPayload() isProctoringEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProctoringEvent) GetGazeDeviation() *GazeDeviationPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProctoringEvent_GazeDeviation); ok {
			return x.GazeDeviation
		}
	}
	return nil
}

func (x *ProctoringEvent) GetFaceDetection() *FaceDetectionPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProctoringEvent_FaceDetection); ok {
			return x.FaceDetection
		}
	}
	return nil
}

func (x *ProctoringEvent) GetObjectDetection() *ObjectDetectionPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProctoringEvent_ObjectDetection); ok {
			return x.ObjectDetection
		}
	}
	return nil
}

func (x *ProctoringEvent) GetAudio() *AudioPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProctoringEvent_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

func (x *ProctoringEvent) GetBrowser() *BrowserPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProctoringEvent_Browser); ok {
			return x.Browser
		}
	}
	return nil
}

func (x *ProctoringEvent) GetSystem() *SystemPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProctoringEvent_System); ok {
			return x.System
		}
	}
	return nil
}

func (x *ProctoringEvent) GetPsychometry() *PsychometryPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProctoringEvent_Psychometry); ok {
			return x.Psychometry
		}
	}
	return nil
}

func (x *ProctoringEvent) GetNetwork() *NetworkPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProctoringEvent_Network); ok {
			return x.Network
		}
	}
	return nil
}

func (x *ProctoringEvent) GetKernel() *KernelPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProctoringEvent_Kernel); ok {
			return x.Kernel
		}
	}
	return nil
}

func (x *ProctoringEvent) GetHeadPose() *HeadPosePayload {
	if x != nil {
		if x, ok := x.Payload.(*ProctoringEvent_HeadPose); ok {
			return x.HeadPose
		}
	}
	return nil
}

func (x *ProctoringEvent) GetLiveness() *LivenessPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProctoringEvent_Liveness); ok {
			return x.Liveness
		}
	}
	return nil
}

func (x *ProctoringEvent) GetAudioAnalysis() *AudioAnalysisPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProctoringEvent_AudioAnalysis); ok {
			return x.AudioAnalysis
		}
	}
	return nil
}

func (x *ProctoringEvent) GetFaceEmbedding() *FaceEmbeddingPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProctoringEvent_FaceEmbedding); ok {
			return x.FaceEmbedding
		}
	}
	return nil
}

func (x *ProctoringEvent) GetClientMeta() *ClientMeta {
	if x != nil {
		return x.ClientMeta
	}
	return nil
}

type isProctoringEvent_Payload interface {
	isProctoringEvent_Payload()
}

type ProctoringEvent_GazeDeviation struct {
	GazeDeviation *GazeDeviationPayload `protobuf:"bytes,20,opt,name=gaze_deviation,json=gazeDeviation,proto3,oneof"`
}

type ProctoringEvent_FaceDetection struct {
	FaceDetection *FaceDetectionPayload `protobuf:"bytes,21,opt,name=face_detection,json=faceDetection,proto3,oneof"`
}

type ProctoringEvent_ObjectDetection struct {
	ObjectDetection *ObjectDetectionPayload `protobuf:"bytes,22,opt,name=object_detection,json=objectDetection,proto3,oneof"`
}

type ProctoringEvent_Audio struct {
	Audio *AudioPayload `protobuf:"bytes,23,opt,name=audio,proto3,oneof"`
}

type ProctoringEvent_Browser struct {
	Browser *BrowserPayload `protobuf:"bytes,24,opt,name=browser,proto3,oneof"`
}

type ProctoringEvent_System struct {
	System *SystemPayload `protobuf:"bytes,25,opt,name=system,proto3,oneof"`
}

type ProctoringEvent_Psychometry struct {
	Psychometry *PsychometryPayload `protobuf:"bytes,26,opt,name=psychometry,proto3,oneof"`
}

type ProctoringEvent_Network struct {
	Network *NetworkPayload `protobuf:"bytes,27,opt,name=network,proto3,oneof"`
}

type ProctoringEvent_Kernel struct {
	Kernel *KernelPayload `protobuf:"bytes,28,opt,name=kernel,proto3,oneof"`
}

type ProctoringEvent_HeadPose struct {
	// AI Vision & Audio payloads
	HeadPose *HeadPosePayload `protobuf:"bytes,29,opt,name=head_pose,json=headPose,proto3,oneof"`
}

type ProctoringEvent_Liveness struct {
	Liveness *LivenessPayload `protobuf:"bytes,31,opt,name=liveness,proto3,oneof"`
}

type ProctoringEvent_AudioAnalysis struct {
	AudioAnalysis *AudioAnalysisPayload `protobuf:"bytes,32,opt,name=audio_analysis,json=audioAnalysis,proto3,oneof"`
}

type ProctoringEvent_FaceEmbedding struct {
	FaceEmbedding *FaceEmbeddingPayload `protobuf:"bytes,33,opt,name=face_embedding,json=faceEmbedding,proto3,oneof"`
}

func (*ProctoringEvent_GazeDeviation) isProctoringEvent_Payload() {}

func (*ProctoringEvent_FaceDetection) isProctoringEvent_Payload() {}

func (*ProctoringEvent_ObjectDetection) isProctoringEvent_Payload() {}

func (*ProctoringEvent_Audio) isProctoringEvent_Payload() {}

func (*ProctoringEvent_Browser) isProctoringEvent_Payload() {}

func (*ProctoringEvent_System) isProctoringEvent_Payload() {}

func (*ProctoringEvent_Psychometry) isProctoringEvent_Payload() {}

func (*ProctoringEvent_Network) isProctoringEvent_Payload() {}

func (*ProctoringEvent_Kernel) isProctoringEvent_Payload() {}

func (*ProctoringEvent_HeadPose) isProctoringEvent_Payload() {}

func (*ProctoringEvent_Liveness) isProctoringEvent_Payload() {}

func (*ProctoringEvent_AudioAnalysis) isProctoringEvent_Payload() {}

func (*ProctoringEvent_FaceEmbedding) isProctoringEvent_Payload() {}

type GazeDeviationPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Direction of gaze deviation.
	Direction string `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"` // "left", "right", "up", "down"
	// Duration of deviation in milliseconds.
	DurationMs int64 `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// Angle of deviation in degrees from center.
	AngleDegrees float32 `protobuf:"fixed32,3,opt,name=angle_degrees,json=angleDegrees,proto3" json:"angle_degrees,omitempty"`
	// Current gaze coordinates (normalized 0-1).
	GazeX         float32 `protobuf:"fixed32,4,opt,name=gaze_x,json=gazeX,proto3" json:"gaze_x,omitempty"`
	GazeY         float32 `protobuf:"fixed32,5,opt,name=gaze_y,json=gazeY,proto3" json:"gaze_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GazeDeviationPayload) Reset() {
	*x = GazeDeviationPayload{}
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GazeDeviationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GazeDeviationPayload) ProtoMessage() {}

func (x *GazeDeviationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GazeDeviationPayload.ProtoReflect.Descriptor instead.
func (*GazeDeviationPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{1}
}

func (x *GazeDeviationPayload) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *GazeDeviationPayload) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *GazeDeviationPayload) GetAngleDegrees() float32 {
	if x != nil {
		return x.AngleDegrees
	}
	return 0
}

func (x *GazeDeviationPayload) GetGazeX() float32 {
	if x != nil {
		return x.GazeX
	}
	return 0
}

func (x *GazeDeviationPayload) GetGazeY() float32 {
	if x != nil {
		return x.GazeY
	}
	return 0
}

type FaceDetectionPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the face matched the registered identity.
	Match bool `protobuf:"varint,1,opt,name=match,proto3" json:"match,omitempty"`
	// Similarity score (0.0 - 1.0).
	Similarity float32 `protobuf:"fixed32,2,opt,name=similarity,proto3" json:"similarity,omitempty"`
	// Number of faces detected in frame.
	FaceCount int32 `protobuf:"varint,3,opt,name=face_count,json=faceCount,proto3" json:"face_count,omitempty"`
	// Spoof detection result.
	IsSpoof bool `protobuf:"varint,4,opt,name=is_spoof,json=isSpoof,proto3" json:"is_spoof,omitempty"`
	// Type of spoof detected (photo, video, mask, deepfake).
	SpoofType     string `protobuf:"bytes,5,opt,name=spoof_type,json=spoofType,proto3" json:"spoof_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaceDetectionPayload) Reset() {
	*x = FaceDetectionPayload{}
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaceDetectionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceDetectionPayload) ProtoMessage() {}

func (x *FaceDetectionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceDetectionPayload.ProtoReflect.Descriptor instead.
func (*FaceDetectionPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{2}
}

func (x *FaceDetectionPayload) GetMatch() bool {
	if x != nil {
		return x.Match
	}
	return false
}

func (x *FaceDetectionPayload) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

func (x *FaceDetectionPayload) GetFaceCount() int32 {
	if x != nil {
		return x.FaceCount
	}
	return 0
}

func (x *FaceDetectionPayload) GetIsSpoof() bool {
	if x != nil {
		return x.IsSpoof
	}
	return false
}

func (x *FaceDetectionPayload) GetSpoofType() string {
	if x != nil {
		return x.SpoofType
	}
	return ""
}

type ObjectDetectionPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of object detected.
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"` // "phone", "book", "earbuds", "tablet"
	// Bounding box coordinates (normalized 0-1).
	BboxX float32 `protobuf:"fixed32,2,opt,name=bbox_x,json=bboxX,proto3" json:"bbox_x,omitempty"`
	BboxY float32 `protobuf:"fixed32,3,opt,name=bbox_y,json=bboxY,proto3" json:"bbox_y,omitempty"`
	BboxW float32 `protobuf:"fixed32,4,opt,name=bbox_w,json=bboxW,proto3" json:"bbox_w,omitempty"`
	BboxH float32 `protobuf:"fixed32,5,opt,name=bbox_h,json=bboxH,proto3" json:"bbox_h,omitempty"`
	// Detection confidence.
	DetectionConfidence float32 `protobuf:"fixed32,6,opt,name=detection_confidence,json=detectionConfidence,proto3" json:"detection_confidence,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ObjectDetectionPayload) Reset() {
	*x = ObjectDetectionPayload{}
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectDetectionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectDetectionPayload) ProtoMessage() {}

func (x *ObjectDetectionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectDetectionPayload.ProtoReflect.Descriptor instead.
func (*ObjectDetectionPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{3}
}

func (x *ObjectDetectionPayload) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *ObjectDetectionPayload) GetBboxX() float32 {
	if x != nil {
		return x.BboxX
	}
	return 0
}

func (x *ObjectDetectionPayload) GetBboxY() float32 {
	if x != nil {
		return x.BboxY
	}
	return 0
}

func (x *ObjectDetectionPayload) GetBboxW() float32 {
	if x != nil {
		return x.BboxW
	}
	return 0
}

func (x *ObjectDetectionPayload) GetBboxH() float32 {
	if x != nil {
		return x.BboxH
	}
	return 0
}

func (x *ObjectDetectionPayload) GetDetectionConfidence() float32 {
	if x != nil {
		return x.DetectionConfidence
	}
	return 0
}

type AudioPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Decibel level.
	DbLevel float32 `protobuf:"fixed32,1,opt,name=db_level,json=dbLevel,proto3" json:"db_level,omitempty"`
	// Whether speech was detected.
	SpeechDetected bool `protobuf:"varint,2,opt,name=speech_detected,json=speechDetected,proto3" json:"speech_detected,omitempty"`
	// Number of distinct speakers identified.
	SpeakerCount int32 `protobuf:"varint,3,opt,name=speaker_count,json=speakerCount,proto3" json:"speaker_count,omitempty"`
	// Classified noise source (keyboard, traffic, music, speech, whisper).
	NoiseSource string `protobuf:"bytes,4,opt,name=noise_source,json=noiseSource,proto3" json:"noise_source,omitempty"`
	// Duration of audio anomaly in milliseconds.
	DurationMs    int64 `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioPayload) Reset() {
	*x = AudioPayload{}
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioPayload) ProtoMessage() {}

func (x *AudioPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioPayload.ProtoReflect.Descriptor instead.
func (*AudioPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{4}
}

func (x *AudioPayload) GetDbLevel() float32 {
	if x != nil {
		return x.DbLevel
	}
	return 0
}

func (x *AudioPayload) GetSpeechDetected() bool {
	if x != nil {
		return x.SpeechDetected
	}
	return false
}

func (x *AudioPayload) GetSpeakerCount() int32 {
	if x != nil {
		return x.SpeakerCount
	}
	return 0
}

func (x *AudioPayload) GetNoiseSource() string {
	if x != nil {
		return x.NoiseSource
	}
	return ""
}

func (x *AudioPayload) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type BrowserPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tab switch count in current session.
	TabSwitchCount int32 `protobuf:"varint,1,opt,name=tab_switch_count,json=tabSwitchCount,proto3" json:"tab_switch_count,omitempty"`
	// URL or tab title (redacted for privacy).
	TargetInfo string `protobuf:"bytes,2,opt,name=target_info,json=targetInfo,proto3" json:"target_info,omitempty"`
	// Whether fullscreen was exited.
	FullscreenExited bool `protobuf:"varint,3,opt,name=fullscreen_exited,json=fullscreenExited,proto3" json:"fullscreen_exited,omitempty"`
	// Number of external displays detected.
	DisplayCount int32 `protobuf:"varint,4,opt,name=display_count,json=displayCount,proto3" json:"display_count,omitempty"`
	// Action attempted (copy, paste, print_screen, context_menu).
	Action        string `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowserPayload) Reset() {
	*x = BrowserPayload{}
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserPayload) ProtoMessage() {}

func (x *BrowserPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserPayload.ProtoReflect.Descriptor instead.
func (*BrowserPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{5}
}

func (x *BrowserPayload) GetTabSwitchCount() int32 {
	if x != nil {
		return x.TabSwitchCount
	}
	return 0
}

func (x *BrowserPayload) GetTargetInfo() string {
	if x != nil {
		return x.TargetInfo
	}
	return ""
}

func (x *BrowserPayload) GetFullscreenExited() bool {
	if x != nil {
		return x.FullscreenExited
	}
	return false
}

func (x *BrowserPayload) GetDisplayCount() int32 {
	if x != nil {
		return x.DisplayCount
	}
	return 0
}

func (x *BrowserPayload) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type SystemPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Process name that triggered the alert.
	ProcessName string `protobuf:"bytes,1,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	// Process ID.
	ProcessId int64 `protobuf:"varint,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	// Whether the process was terminated.
	Terminated bool `protobuf:"varint,3,opt,name=terminated,proto3" json:"terminated,omitempty"`
	// Category of violation (remote_access, vm, screen_capture).
	Category      string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemPayload) Reset() {
	*x = SystemPayload{}
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemPayload) ProtoMessage() {}

func (x *SystemPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemPayload.ProtoReflect.Descriptor instead.
func (*SystemPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{6}
}

func (x *SystemPayload) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *SystemPayload) GetProcessId() int64 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *SystemPayload) GetTerminated() bool {
	if x != nil {
		return x.Terminated
	}
	return false
}

func (x *SystemPayload) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type PsychometryPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Emotion classification (stress, confidence, confusion, neutral).
	Emotion string `protobuf:"bytes,1,opt,name=emotion,proto3" json:"emotion,omitempty"`
	// Intensity score (0.0 - 1.0).
	Intensity float32 `protobuf:"fixed32,2,opt,name=intensity,proto3" json:"intensity,omitempty"`
	// Focus loss score (0.0 - 1.0, lower = worse focus).
	FocusScore float32 `protobuf:"fixed32,3,opt,name=focus_score,json=focusScore,proto3" json:"focus_score,omitempty"`
	// Blink rate per minute.
	BlinkRate float32 `protobuf:"fixed32,4,opt,name=blink_rate,json=blinkRate,proto3" json:"blink_rate,omitempty"`
	// Whether blink pattern is anomalous.
	BlinkAnomaly  bool `protobuf:"varint,5,opt,name=blink_anomaly,json=blinkAnomaly,proto3" json:"blink_anomaly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PsychometryPayload) Reset() {
	*x = PsychometryPayload{}
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PsychometryPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PsychometryPayload) ProtoMessage() {}

func (x *PsychometryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PsychometryPayload.ProtoReflect.Descriptor instead.
func (*PsychometryPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{7}
}

func (x *PsychometryPayload) GetEmotion() string {
	if x != nil {
		return x.Emotion
	}
	return ""
}

func (x *PsychometryPayload) GetIntensity() float32 {
	if x != nil {
		return x.Intensity
	}
	return 0
}

func (x *PsychometryPayload) GetFocusScore() float32 {
	if x != nil {
		return x.FocusScore
	}
	return 0
}

func (x *PsychometryPayload) GetBlinkRate() float32 {
	if x != nil {
		return x.BlinkRate
	}
	return 0
}

func (x *PsychometryPayload) GetBlinkAnomaly() bool {
	if x != nil {
		return x.BlinkAnomaly
	}
	return false
}

type NetworkPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of detection (vpn, proxy, tor, suspicious_device).
	DetectionType string `protobuf:"bytes,1,opt,name=detection_type,json=detectionType,proto3" json:"detection_type,omitempty"`
	// IP address or network identifier (hashed for privacy).
	NetworkHash string `protobuf:"bytes,2,opt,name=network_hash,json=networkHash,proto3" json:"network_hash,omitempty"`
	// Number of suspicious devices on local network.
	SuspiciousDeviceCount int32 `protobuf:"varint,3,opt,name=suspicious_device_count,json=suspiciousDeviceCount,proto3" json:"suspicious_device_count,omitempty"`
	// VPN/proxy provider name if identified.
	Provider      string `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPayload) Reset() {
	*x = NetworkPayload{}
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPayload) ProtoMessage() {}

func (x *NetworkPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPayload.ProtoReflect.Descriptor instead.
func (*NetworkPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkPayload) GetDetectionType() string {
	if x != nil {
		return x.DetectionType
	}
	return ""
}

func (x *NetworkPayload) GetNetworkHash() string {
	if x != nil {
		return x.NetworkHash
	}
	return ""
}

func (x *NetworkPayload) GetSuspiciousDeviceCount() int32 {
	if x != nil {
		return x.SuspiciousDeviceCount
	}
	return 0
}

func (x *NetworkPayload) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type KernelPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Typing dynamics — words per minute.
	Wpm float32 `protobuf:"fixed32,1,opt,name=wpm,proto3" json:"wpm,omitempty"`
	// Typing dynamics — keystroke latency standard deviation.
	KeystrokeStdDevMs float32 `protobuf:"fixed32,2,opt,name=keystroke_std_dev_ms,json=keystrokeStdDevMs,proto3" json:"keystroke_std_dev_ms,omitempty"`
	// Whether hand was detected on mouse during cursor movement.
	HandOnMouse bool `protobuf:"varint,3,opt,name=hand_on_mouse,json=handOnMouse,proto3" json:"hand_on_mouse,omitempty"`
	// Hardware ID hash for binding verification.
	HardwareIdHash string `protobuf:"bytes,4,opt,name=hardware_id_hash,json=hardwareIdHash,proto3" json:"hardware_id_hash,omitempty"`
	// Mismatched component (cpu, motherboard, gpu).
	MismatchComponent string `protobuf:"bytes,5,opt,name=mismatch_component,json=mismatchComponent,proto3" json:"mismatch_component,omitempty"`
	// Number of monitors detected at kernel level.
	MonitorCount int32 `protobuf:"varint,6,opt,name=monitor_count,json=monitorCount,proto3" json:"monitor_count,omitempty"`
	// Whether any monitor is virtual.
	VirtualMonitor bool `protobuf:"varint,7,opt,name=virtual_monitor,json=virtualMonitor,proto3" json:"virtual_monitor,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KernelPayload) Reset() {
	*x = KernelPayload{}
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelPayload) ProtoMessage() {}

func (x *KernelPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelPayload.ProtoReflect.Descriptor instead.
func (*KernelPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{9}
}

func (x *KernelPayload) GetWpm() float32 {
	if x != nil {
		return x.Wpm
	}
	return 0
}

func (x *KernelPayload) GetKeystrokeStdDevMs() float32 {
	if x != nil {
		return x.KeystrokeStdDevMs
	}
	return 0
}

func (x *KernelPayload) GetHandOnMouse() bool {
	if x != nil {
		return x.HandOnMouse
	}
	return false
}

func (x *KernelPayload) GetHardwareIdHash() string {
	if x != nil {
		return x.HardwareIdHash
	}
	return ""
}

func (x *KernelPayload) GetMismatchComponent() string {
	if x != nil {
		return x.MismatchComponent
	}
	return ""
}

func (x *KernelPayload) GetMonitorCount() int32 {
	if x != nil {
		return x.MonitorCount
	}
	return 0
}

func (x *KernelPayload) GetVirtualMonitor() bool {
	if x != nil {
		return x.VirtualMonitor
	}
	return false
}

// Head pose estimation from 3D face landmark regression.
// Euler angles in degrees; (0,0,0) = facing camera directly.
type HeadPosePayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Yaw: horizontal rotation. Negative = looking left, positive = right.
	Yaw float32 `protobuf:"fixed32,1,opt,name=yaw,proto3" json:"yaw,omitempty"`
	// Pitch: vertical rotation. Negative = looking down, positive = up.
	Pitch float32 `protobuf:"fixed32,2,opt,name=pitch,proto3" json:"pitch,omitempty"`
	// Roll: in-plane rotation. Negative = tilted left, positive = right.
	Roll float32 `protobuf:"fixed32,3,opt,name=roll,proto3" json:"roll,omitempty"`
	// Face bounding box (normalized 0-1 of frame dimensions).
	FaceX float32 `protobuf:"fixed32,4,opt,name=face_x,json=faceX,proto3" json:"face_x,omitempty"`
	FaceY float32 `protobuf:"fixed32,5,opt,name=face_y,json=faceY,proto3" json:"face_y,omitempty"`
	FaceW float32 `protobuf:"fixed32,6,opt,name=face_w,json=faceW,proto3" json:"face_w,omitempty"`
	FaceH float32 `protobuf:"fixed32,7,opt,name=face_h,json=faceH,proto3" json:"face_h,omitempty"`
	// Inter-pupillary distance in pixels (proxy for distance-to-camera).
	IpdPx float32 `protobuf:"fixed32,8,opt,name=ipd_px,json=ipdPx,proto3" json:"ipd_px,omitempty"`
	// Number of 3D landmarks used (68 or 478 for MediaPipe).
	LandmarkCount int32 `protobuf:"varint,9,opt,name=landmark_count,json=landmarkCount,proto3" json:"landmark_count,omitempty"`
	// Inference latency in milliseconds (for performance monitoring).
	InferenceMs   float32 `protobuf:"fixed32,10,opt,name=inference_ms,json=inferenceMs,proto3" json:"inference_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadPosePayload) Reset() {
	*x = HeadPosePayload{}
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadPosePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadPosePayload) ProtoMessage() {}

func (x *HeadPosePayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadPosePayload.ProtoReflect.Descriptor instead.
func (*HeadPosePayload) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{10}
}

func (x *HeadPosePayload) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *HeadPosePayload) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *HeadPosePayload) GetRoll() float32 {
	if x != nil {
		return x.Roll
	}
	return 0
}

func (x *HeadPosePayload) GetFaceX() float32 {
	if x != nil {
		return x.FaceX
	}
	return 0
}

func (x *HeadPosePayload) GetFaceY() float32 {
	if x != nil {
		return x.FaceY
	}
	return 0
}

func (x *HeadPosePayload) GetFaceW() float32 {
	if x != nil {
		return x.FaceW
	}
	return 0
}

func (x *HeadPosePayload) GetFaceH() float32 {
	if x != nil {
		return x.FaceH
	}
	return 0
}

func (x *HeadPosePayload) GetIpdPx() float32 {
	if x != nil {
		return x.IpdPx
	}
	return 0
}

func (x *HeadPosePayload) GetLandmarkCount() int32 {
	if x != nil {
		return x.LandmarkCount
	}
	return 0
}

func (x *HeadPosePayload) GetInferenceMs() float32 {
	if x != nil {
		return x.InferenceMs
	}
	return 0
}

// Liveness verification payload — multi-factor anti-spoofing.
type LivenessPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall liveness probability (0.0 = spoof, 1.0 = real).
	LivenessScore float32 `protobuf:"fixed32,1,opt,name=liveness_score,json=livenessScore,proto3" json:"liveness_score,omitempty"`
	// Eye-blink detection: true if natural blink pattern detected.
	BlinkDetected bool `protobuf:"varint,2,opt,name=blink_detected,json=blinkDetected,proto3" json:"blink_detected,omitempty"`
	// Blink rate per minute over sliding window.
	BlinkRatePerMin float32 `protobuf:"fixed32,3,opt,name=blink_rate_per_min,json=blinkRatePerMin,proto3" json:"blink_rate_per_min,omitempty"`
	// Texture analysis score (detects printed photos, screen replays).
	TextureScore float32 `protobuf:"fixed32,4,opt,name=texture_score,json=textureScore,proto3" json:"texture_score,omitempty"`
	// Depth consistency score (detects flat surfaces like photos/screens).
	DepthScore float32 `protobuf:"fixed32,5,opt,name=depth_score,json=depthScore,proto3" json:"depth_score,omitempty"`
	// Type of spoof suspected if liveness_score < threshold.
	SpoofVector string `protobuf:"bytes,6,opt,name=spoof_vector,json=spoofVector,proto3" json:"spoof_vector,omitempty"` // "photo", "screen_replay", "mask", "deepfake", "none"
	// Frame quality score (blur, exposure, occlusion).
	FrameQuality  float32 `protobuf:"fixed32,7,opt,name=frame_quality,json=frameQuality,proto3" json:"frame_quality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LivenessPayload) Reset() {
	*x = LivenessPayload{}
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivenessPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivenessPayload) ProtoMessage() {}

func (x *LivenessPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivenessPayload.ProtoReflect.Descriptor instead.
func (*LivenessPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{11}
}

func (x *LivenessPayload) GetLivenessScore() float32 {
	if x != nil {
		return x.LivenessScore
	}
	return 0
}

func (x *LivenessPayload) GetBlinkDetected() bool {
	if x != nil {
		return x.BlinkDetected
	}
	return false
}

func (x *LivenessPayload) GetBlinkRatePerMin() float32 {
	if x != nil {
		return x.BlinkRatePerMin
	}
	return 0
}

func (x *LivenessPayload) GetTextureScore() float32 {
	if x != nil {
		return x.TextureScore
	}
	return 0
}

func (x *LivenessPayload) GetDepthScore() float32 {
	if x != nil {
		return x.DepthScore
	}
	return 0
}

func (x *LivenessPayload) GetSpoofVector() string {
	if x != nil {
		return x.SpoofVector
	}
	return ""
}

func (x *LivenessPayload) GetFrameQuality() float32 {
	if x != nil {
		return x.FrameQuality
	}
	return 0
}

// Face embedding for continuous identity verification.
type FaceEmbeddingPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 512-dimensional face embedding vector (ArcFace/FaceNet).
	Embedding []float32 `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	// Cosine similarity to enrolled reference embedding.
	Similarity float32 `protobuf:"fixed32,2,opt,name=similarity,proto3" json:"similarity,omitempty"`
	// Whether identity match passed threshold (>0.65 = match).
	IdentityMatch bool `protobuf:"varint,3,opt,name=identity_match,json=identityMatch,proto3" json:"identity_match,omitempty"`
	// Embedding model version for forward compatibility.
	ModelVersion string `protobuf:"bytes,4,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	// Face alignment quality (0-1, pre-embedding).
	AlignmentQuality float32 `protobuf:"fixed32,5,opt,name=alignment_quality,json=alignmentQuality,proto3" json:"alignment_quality,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FaceEmbeddingPayload) Reset() {
	*x = FaceEmbeddingPayload{}
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaceEmbeddingPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceEmbeddingPayload) ProtoMessage() {}

func (x *FaceEmbeddingPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceEmbeddingPayload.ProtoReflect.Descriptor instead.
func (*FaceEmbeddingPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{12}
}

func (x *FaceEmbeddingPayload) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *FaceEmbeddingPayload) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

func (x *FaceEmbeddingPayload) GetIdentityMatch() bool {
	if x != nil {
		return x.IdentityMatch
	}
	return false
}

func (x *FaceEmbeddingPayload) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *FaceEmbeddingPayload) GetAlignmentQuality() float32 {
	if x != nil {
		return x.AlignmentQuality
	}
	return 0
}

// Audio analysis payload — sound activity detection + anomaly classification.
// All processing is local (browser-side). No raw audio leaves the device.
type AudioAnalysisPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RMS dB level (calibrated, A-weighted).
	RmsDb float32 `protobuf:"fixed32,1,opt,name=rms_db,json=rmsDb,proto3" json:"rms_db,omitempty"`
	// Voice Activity Detection result.
	VadActive bool `protobuf:"varint,2,opt,name=vad_active,json=vadActive,proto3" json:"vad_active,omitempty"`
	// VAD confidence (0-1).
	VadConfidence float32 `protobuf:"fixed32,3,opt,name=vad_confidence,json=vadConfidence,proto3" json:"vad_confidence,omitempty"`
	// Spectral centroid in Hz (voice ~300-3000Hz, music ~1000-8000Hz).
	SpectralCentroidHz float32 `protobuf:"fixed32,4,opt,name=spectral_centroid_hz,json=spectralCentroidHz,proto3" json:"spectral_centroid_hz,omitempty"`
	// Zero-crossing rate (speech ~0.02-0.10, noise >0.10).
	Zcr float32 `protobuf:"fixed32,5,opt,name=zcr,proto3" json:"zcr,omitempty"`
	// Classified audio source.
	Classification string `protobuf:"bytes,6,opt,name=classification,proto3" json:"classification,omitempty"` // "silence", "speech", "whisper", "music", "keyboard", "ambient"
	// Classification confidence (0-1).
	ClassificationConfidence float32 `protobuf:"fixed32,7,opt,name=classification_confidence,json=classificationConfidence,proto3" json:"classification_confidence,omitempty"`
	// Number of distinct speakers detected (speaker diarization).
	SpeakerCount int32 `protobuf:"varint,8,opt,name=speaker_count,json=speakerCount,proto3" json:"speaker_count,omitempty"`
	// Whether detected voice matches enrolled voiceprint.
	SpeakerMatch bool `protobuf:"varint,9,opt,name=speaker_match,json=speakerMatch,proto3" json:"speaker_match,omitempty"`
	// Speaker embedding cosine similarity to enrolled reference.
	SpeakerSimilarity float32 `protobuf:"fixed32,10,opt,name=speaker_similarity,json=speakerSimilarity,proto3" json:"speaker_similarity,omitempty"`
	// Duration of current audio segment in milliseconds.
	SegmentDurationMs int64 `protobuf:"varint,11,opt,name=segment_duration_ms,json=segmentDurationMs,proto3" json:"segment_duration_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AudioAnalysisPayload) Reset() {
	*x = AudioAnalysisPayload{}
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioAnalysisPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioAnalysisPayload) ProtoMessage() {}

func (x *AudioAnalysisPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioAnalysisPayload.ProtoReflect.Descriptor instead.
func (*AudioAnalysisPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{13}
}

func (x *AudioAnalysisPayload) GetRmsDb() float32 {
	if x != nil {
		return x.RmsDb
	}
	return 0
}

func (x *AudioAnalysisPayload) GetVadActive() bool {
	if x != nil {
		return x.VadActive
	}
	return false
}

func (x *AudioAnalysisPayload) GetVadConfidence() float32 {
	if x != nil {
		return x.VadConfidence
	}
	return 0
}

func (x *AudioAnalysisPayload) GetSpectralCentroidHz() float32 {
	if x != nil {
		return x.SpectralCentroidHz
	}
	return 0
}

func (x *AudioAnalysisPayload) GetZcr() float32 {
	if x != nil {
		return x.Zcr
	}
	return 0
}

func (x *AudioAnalysisPayload) GetClassification() string {
	if x != nil {
		return x.Classification
	}
	return ""
}

func (x *AudioAnalysisPayload) GetClassificationConfidence() float32 {
	if x != nil {
		return x.ClassificationConfidence
	}
	return 0
}

func (x *AudioAnalysisPayload) GetSpeakerCount() int32 {
	if x != nil {
		return x.SpeakerCount
	}
	return 0
}

func (x *AudioAnalysisPayload) GetSpeakerMatch() bool {
	if x != nil {
		return x.SpeakerMatch
	}
	return false
}

func (x *AudioAnalysisPayload) GetSpeakerSimilarity() float32 {
	if x != nil {
		return x.SpeakerSimilarity
	}
	return 0
}

func (x *AudioAnalysisPayload) GetSegmentDurationMs() int64 {
	if x != nil {
		return x.SegmentDurationMs
	}
	return 0
}

type ClientMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Browser user agent (for compatibility tracking, NOT fingerprinting).
	UserAgent string `protobuf:"bytes,1,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// Client SDK version.
	SdkVersion string `protobuf:"bytes,2,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	// Screen resolution.
	Resolution string `protobuf:"bytes,3,opt,name=resolution,proto3" json:"resolution,omitempty"`
	// Client timezone offset in minutes from UTC.
	TimezoneOffsetMin int32 `protobuf:"varint,4,opt,name=timezone_offset_min,json=timezoneOffsetMin,proto3" json:"timezone_offset_min,omitempty"`
	// IP address (set server-side, never trusted from client).
	IpAddress string `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// Region derived from IP (set server-side).
	Region        string `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMeta) Reset() {
	*x = ClientMeta{}
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMeta) ProtoMessage() {}

func (x *ClientMeta) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMeta.ProtoReflect.Descriptor instead.
func (*ClientMeta) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{14}
}

func (x *ClientMeta) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *ClientMeta) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *ClientMeta) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *ClientMeta) GetTimezoneOffsetMin() int32 {
	if x != nil {
		return x.TimezoneOffsetMin
	}
	return 0
}

func (x *ClientMeta) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *ClientMeta) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type IngestEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *ProctoringEvent       `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventRequest) Reset() {
	*x = IngestEventRequest{}
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventRequest) ProtoMessage() {}

func (x *IngestEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventRequest.ProtoReflect.Descriptor instead.
func (*IngestEventRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{15}
}

func (x *IngestEventRequest) GetEvent() *ProctoringEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type IngestEventResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Accepted bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	EventId  string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Server-assigned sequence number for ordering guarantees.
	Sequence      int64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventResponse) Reset() {
	*x = IngestEventResponse{}
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventResponse) ProtoMessage() {}

func (x *IngestEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventResponse.ProtoReflect.Descriptor instead.
func (*IngestEventResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{16}
}

func (x *IngestEventResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *IngestEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *IngestEventResponse) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type IngestBatchRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Events []*ProctoringEvent     `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	// Client-assigned batch ID for deduplication.
	BatchId       string `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestBatchRequest) Reset() {
	*x = IngestBatchRequest{}
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestBatchRequest) ProtoMessage() {}

func (x *IngestBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestBatchRequest.ProtoReflect.Descriptor instead.
func (*IngestBatchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{17}
}

func (x *IngestBatchRequest) GetEvents() []*ProctoringEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *IngestBatchRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type IngestBatchResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AcceptedCount    int32                  `protobuf:"varint,1,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	RejectedCount    int32                  `protobuf:"varint,2,opt,name=rejected_count,json=rejectedCount,proto3" json:"rejected_count,omitempty"`
	RejectedEventIds []string               `protobuf:"bytes,3,rep,name=rejected_event_ids,json=rejectedEventIds,proto3" json:"rejected_event_ids,omitempty"`
	// Server-assigned batch sequence.
	BatchSequence int64 `protobuf:"varint,4,opt,name=batch_sequence,json=batchSequence,proto3" json:"batch_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestBatchResponse) Reset() {
	*x = IngestBatchResponse{}
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestBatchResponse) ProtoMessage() {}

func (x *IngestBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestBatchResponse.ProtoReflect.Descriptor instead.
func (*IngestBatchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{18}
}

func (x *IngestBatchResponse) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *IngestBatchResponse) GetRejectedCount() int32 {
	if x != nil {
		return x.RejectedCount
	}
	return 0
}

func (x *IngestBatchResponse) GetRejectedEventIds() []string {
	if x != nil {
		return x.RejectedEventIds
	}
	return nil
}

func (x *IngestBatchResponse) GetBatchSequence() int64 {
	if x != nil {
		return x.BatchSequence
	}
	return 0
}

type StreamAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Accepted      bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAck) Reset() {
	*x = StreamAck{}
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAck) ProtoMessage() {}

func (x *StreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAck.ProtoReflect.Descriptor instead.
func (*StreamAck) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{19}
}

func (x *StreamAck) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *StreamAck) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *StreamAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type HeartbeatRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StudentId       string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	ExamId          string                 `protobuf:"bytes,3,opt,name=exam_id,json=examId,proto3" json:"exam_id,omitempty"`
	ClientTimestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=client_timestamp,json=clientTimestamp,proto3" json:"client_timestamp,omitempty"`
	// Current integrity metrics snapshot.
	CurrentFocusScore float32 `protobuf:"fixed32,5,opt,name=current_focus_score,json=currentFocusScore,proto3" json:"current_focus_score,omitempty"`
	ViolationCount    int32   `protobuf:"varint,6,opt,name=violation_count,json=violationCount,proto3" json:"violation_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{20}
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HeartbeatRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *HeartbeatRequest) GetExamId() string {
	if x != nil {
		return x.ExamId
	}
	return ""
}

func (x *HeartbeatRequest) GetClientTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ClientTimestamp
	}
	return nil
}

func (x *HeartbeatRequest) GetCurrentFocusScore() float32 {
	if x != nil {
		return x.CurrentFocusScore
	}
	return 0
}

func (x *HeartbeatRequest) GetViolationCount() int32 {
	if x != nil {
		return x.ViolationCount
	}
	return 0
}

type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionActive   bool                   `protobuf:"varint,1,opt,name=session_active,json=sessionActive,proto3" json:"session_active,omitempty"`
	ServerTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	// Server can instruct client to adjust settings dynamically.
	Directive     *SessionDirective `protobuf:"bytes,3,opt,name=directive,proto3" json:"directive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{21}
}

func (x *HeartbeatResponse) GetSessionActive() bool {
	if x != nil {
		return x.SessionActive
	}
	return false
}

func (x *HeartbeatResponse) GetServerTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTimestamp
	}
	return nil
}

func (x *HeartbeatResponse) GetDirective() *SessionDirective {
	if x != nil {
		return x.Directive
	}
	return nil
}

type SessionDirective struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether to increase/decrease telemetry frequency.
	TelemetryMode TelemetryMode `protobuf:"varint,1,opt,name=telemetry_mode,json=telemetryMode,proto3,enum=argus.eventcollector.v1.TelemetryMode" json:"telemetry_mode,omitempty"`
	// Whether the session should be terminated.
	Terminate bool `protobuf:"varint,2,opt,name=terminate,proto3" json:"terminate,omitempty"`
	// Reason for termination.
	TerminateReason string `protobuf:"bytes,3,opt,name=terminate_reason,json=terminateReason,proto3" json:"terminate_reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionDirective) Reset() {
	*x = SessionDirective{}
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionDirective) ProtoMessage() {}

func (x *SessionDirective) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_event_collector_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionDirective.ProtoReflect.Descriptor instead.
func (*SessionDirective) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_event_collector_proto_rawDescGZIP(), []int{22}
}

func (x *SessionDirective) GetTelemetryMode() TelemetryMode {
	if x != nil {
		return x.TelemetryMode
	}
	return TelemetryMode_TELEMETRY_NORMAL
}

func (x *SessionDirective) GetTerminate() bool {
	if x != nil {
		return x.Terminate
	}
	return false
}

func (x *SessionDirective) GetTerminateReason() string {
	if x != nil {
		return x.TerminateReason
	}
	return ""
}

var File_api_proto_v1_event_collector_proto protoreflect.FileDescriptor

const file_api_proto_v1_event_collector_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/v1/event_collector.proto\x12\x17argus.eventcollector.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\r\n" +
	"\x0fProctoringEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x03 \x01(\tR\tstudentId\x12\x17\n" +
	"\aexam_id\x18\x04 \x01(\tR\x06examId\x12\x15\n" +
	"\x06org_id\x18\x05 \x01(\tR\x05orgId\x12A\n" +
	"\n" +
	"event_type\x18\x06 \x01(\x0e2\".argus.eventcollector.v1.EventTypeR\teventType\x12=\n" +
	"\bseverity\x18\a \x01(\x0e2!.argus.eventcollector.v1.SeverityR\bseverity\x12<\n" +
	"\x06source\x18\b \x01(\x0e2$.argus.eventcollector.v1.EventSourceR\x06source\x12E\n" +
	"\x10server_timestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0fserverTimestamp\x12E\n" +
	"\x10client_timestamp\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x0fclientTimestamp\x12.\n" +
	"\x13video_timestamp_sec\x18\v \x01(\x01R\x11videoTimestampSec\x12\x14\n" +
	"\x05label\x18\f \x01(\tR\x05label\x12\x1e\n" +
	"\n" +
	"confidence\x18\r \x01(\x02R\n" +
	"confidence\x12V\n" +
	"\x0egaze_deviation\x18\x14 \x01(\v2-.argus.eventcollector.v1.GazeDeviationPayloadH\x00R\rgazeDeviation\x12V\n" +
	"\x0eface_detection\x18\x15 \x01(\v2-.argus.eventcollector.v1.FaceDetectionPayloadH\x00R\rfaceDetection\x12\\\n" +
	"\x10object_detection\x18\x16 \x01(\v2/.argus.eventcollector.v1.ObjectDetectionPayloadH\x00R\x0fobjectDetection\x12=\n" +
	"\x05audio\x18\x17 \x01(\v2%.argus.eventcollector.v1.AudioPayloadH\x00R\x05audio\x12C\n" +
	"\abrowser\x18\x18 \x01(\v2'.argus.eventcollector.v1.BrowserPayloadH\x00R\abrowser\x12@\n" +
	"\x06system\x18\x19 \x01(\v2&.argus.eventcollector.v1.SystemPayloadH\x00R\x06system\x12O\n" +
	"\vpsychometry\x18\x1a \x01(\v2+.argus.eventcollector.v1.PsychometryPayloadH\x00R\vpsychometry\x12C\n" +
	"\anetwork\x18\x1b \x01(\v2'.argus.eventcollector.v1.NetworkPayloadH\x00R\anetwork\x12@\n" +
	"\x06kernel\x18\x1c \x01(\v2&.argus.eventcollector.v1.KernelPayloadH\x00R\x06kernel\x12G\n" +
	"\thead_pose\x18\x1d \x01(\v2(.argus.eventcollector.v1.HeadPosePayloadH\x00R\bheadPose\x12F\n" +
	"\bliveness\x18\x1f \x01(\v2(.argus.eventcollector.v1.LivenessPayloadH\x00R\bliveness\x12V\n" +
	"\x0eaudio_analysis\x18  \x01(\v2-.argus.eventcollector.v1.AudioAnalysisPayloadH\x00R\raudioAnalysis\x12V\n" +
	"\x0eface_embedding\x18! \x01(\v2-.argus.eventcollector.v1.FaceEmbeddingPayloadH\x00R\rfaceEmbedding\x12D\n" +
	"\vclient_meta\x18\x1e \x01(\v2#.argus.eventcollector.v1.ClientMetaR\n" +
	"clientMetaB\t\n" +
	"\apayload\"\xa8\x01\n" +
	"\x14GazeDeviationPayload\x12\x1c\n" +
	"\tdirection\x18\x01 \x01(\tR\tdirection\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\x03R\n" +
	"durationMs\x12#\n" +
	"\rangle_degrees\x18\x03 \x01(\x02R\fangleDegrees\x12\x15\n" +
	"\x06gaze_x\x18\x04 \x01(\x02R\x05gazeX\x12\x15\n" +
	"\x06gaze_y\x18\x05 \x01(\x02R\x05gazeY\"\xa5\x01\n" +
	"\x14FaceDetectionPayload\x12\x14\n" +
	"\x05match\x18\x01 \x01(\bR\x05match\x12\x1e\n" +
	"\n" +
	"similarity\x18\x02 \x01(\x02R\n" +
	"similarity\x12\x1d\n" +
	"\n" +
	"face_count\x18\x03 \x01(\x05R\tfaceCount\x12\x19\n" +
	"\bis_spoof\x18\x04 \x01(\bR\aisSpoof\x12\x1d\n" +
	"\n" +
	"spoof_type\x18\x05 \x01(\tR\tspoofType\"\xc8\x01\n" +
	"\x16ObjectDetectionPayload\x12\x1f\n" +
	"\vobject_type\x18\x01 \x01(\tR\n" +
	"objectType\x12\x15\n" +
	"\x06bbox_x\x18\x02 \x01(\x02R\x05bboxX\x12\x15\n" +
	"\x06bbox_y\x18\x03 \x01(\x02R\x05bboxY\x12\x15\n" +
	"\x06bbox_w\x18\x04 \x01(\x02R\x05bboxW\x12\x15\n" +
	"\x06bbox_h\x18\x05 \x01(\x02R\x05bboxH\x121\n" +
	"\x14detection_confidence\x18\x06 \x01(\x02R\x13detectionConfidence\"\xbb\x01\n" +
	"\fAudioPayload\x12\x19\n" +
	"\bdb_level\x18\x01 \x01(\x02R\adbLevel\x12'\n" +
	"\x0fspeech_detected\x18\x02 \x01(\bR\x0espeechDetected\x12#\n" +
	"\rspeaker_count\x18\x03 \x01(\x05R\fspeakerCount\x12!\n" +
	"\fnoise_source\x18\x04 \x01(\tR\vnoiseSource\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\"\xc5\x01\n" +
	"\x0eBrowserPayload\x12(\n" +
	"\x10tab_switch_count\x18\x01 \x01(\x05R\x0etabSwitchCount\x12\x1f\n" +
	"\vtarget_info\x18\x02 \x01(\tR\n" +
	"targetInfo\x12+\n" +
	"\x11fullscreen_exited\x18\x03 \x01(\bR\x10fullscreenExited\x12#\n" +
	"\rdisplay_count\x18\x04 \x01(\x05R\fdisplayCount\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\"\x8d\x01\n" +
	"\rSystemPayload\x12!\n" +
	"\fprocess_name\x18\x01 \x01(\tR\vprocessName\x12\x1d\n" +
	"\n" +
	"process_id\x18\x02 \x01(\x03R\tprocessId\x12\x1e\n" +
	"\n" +
	"terminated\x18\x03 \x01(\bR\n" +
	"terminated\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\"\xb1\x01\n" +
	"\x12PsychometryPayload\x12\x18\n" +
	"\aemotion\x18\x01 \x01(\tR\aemotion\x12\x1c\n" +
	"\tintensity\x18\x02 \x01(\x02R\tintensity\x12\x1f\n" +
	"\vfocus_score\x18\x03 \x01(\x02R\n" +
	"focusScore\x12\x1d\n" +
	"\n" +
	"blink_rate\x18\x04 \x01(\x02R\tblinkRate\x12#\n" +
	"\rblink_anomaly\x18\x05 \x01(\bR\fblinkAnomaly\"\xae\x01\n" +
	"\x0eNetworkPayload\x12%\n" +
	"\x0edetection_type\x18\x01 \x01(\tR\rdetectionType\x12!\n" +
	"\fnetwork_hash\x18\x02 \x01(\tR\vnetworkHash\x126\n" +
	"\x17suspicious_device_count\x18\x03 \x01(\x05R\x15suspiciousDeviceCount\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\"\x9d\x02\n" +
	"\rKernelPayload\x12\x10\n" +
	"\x03wpm\x18\x01 \x01(\x02R\x03wpm\x12/\n" +
	"\x14keystroke_std_dev_ms\x18\x02 \x01(\x02R\x11keystrokeStdDevMs\x12\"\n" +
	"\rhand_on_mouse\x18\x03 \x01(\bR\vhandOnMouse\x12(\n" +
	"\x10hardware_id_hash\x18\x04 \x01(\tR\x0ehardwareIdHash\x12-\n" +
	"\x12mismatch_component\x18\x05 \x01(\tR\x11mismatchComponent\x12#\n" +
	"\rmonitor_count\x18\x06 \x01(\x05R\fmonitorCount\x12'\n" +
	"\x0fvirtual_monitor\x18\a \x01(\bR\x0evirtualMonitor\"\x8a\x02\n" +
	"\x0fHeadPosePayload\x12\x10\n" +
	"\x03yaw\x18\x01 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\x02 \x01(\x02R\x05pitch\x12\x12\n" +
	"\x04roll\x18\x03 \x01(\x02R\x04roll\x12\x15\n" +
	"\x06face_x\x18\x04 \x01(\x02R\x05faceX\x12\x15\n" +
	"\x06face_y\x18\x05 \x01(\x02R\x05faceY\x12\x15\n" +
	"\x06face_w\x18\x06 \x01(\x02R\x05faceW\x12\x15\n" +
	"\x06face_h\x18\a \x01(\x02R\x05faceH\x12\x15\n" +
	"\x06ipd_px\x18\b \x01(\x02R\x05ipdPx\x12%\n" +
	"\x0elandmark_count\x18\t \x01(\x05R\rlandmarkCount\x12!\n" +
	"\finference_ms\x18\n" +
	" \x01(\x02R\vinferenceMs\"\x9a\x02\n" +
	"\x0fLivenessPayload\x12%\n" +
	"\x0eliveness_score\x18\x01 \x01(\x02R\rlivenessScore\x12%\n" +
	"\x0eblink_detected\x18\x02 \x01(\bR\rblinkDetected\x12+\n" +
	"\x12blink_rate_per_min\x18\x03 \x01(\x02R\x0fblinkRatePerMin\x12#\n" +
	"\rtexture_score\x18\x04 \x01(\x02R\ftextureScore\x12\x1f\n" +
	"\vdepth_score\x18\x05 \x01(\x02R\n" +
	"depthScore\x12!\n" +
	"\fspoof_vector\x18\x06 \x01(\tR\vspoofVector\x12#\n" +
	"\rframe_quality\x18\a \x01(\x02R\fframeQuality\"\xcd\x01\n" +
	"\x14FaceEmbeddingPayload\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\x12\x1e\n" +
	"\n" +
	"similarity\x18\x02 \x01(\x02R\n" +
	"similarity\x12%\n" +
	"\x0eidentity_match\x18\x03 \x01(\bR\ridentityMatch\x12#\n" +
	"\rmodel_version\x18\x04 \x01(\tR\fmodelVersion\x12+\n" +
	"\x11alignment_quality\x18\x05 \x01(\x02R\x10alignmentQuality\"\xc5\x03\n" +
	"\x14AudioAnalysisPayload\x12\x15\n" +
	"\x06rms_db\x18\x01 \x01(\x02R\x05rmsDb\x12\x1d\n" +
	"\n" +
	"vad_active\x18\x02 \x01(\bR\tvadActive\x12%\n" +
	"\x0evad_confidence\x18\x03 \x01(\x02R\rvadConfidence\x120\n" +
	"\x14spectral_centroid_hz\x18\x04 \x01(\x02R\x12spectralCentroidHz\x12\x10\n" +
	"\x03zcr\x18\x05 \x01(\x02R\x03zcr\x12&\n" +
	"\x0eclassification\x18\x06 \x01(\tR\x0eclassification\x12;\n" +
	"\x19classification_confidence\x18\a \x01(\x02R\x18classificationConfidence\x12#\n" +
	"\rspeaker_count\x18\b \x01(\x05R\fspeakerCount\x12#\n" +
	"\rspeaker_match\x18\t \x01(\bR\fspeakerMatch\x12-\n" +
	"\x12speaker_similarity\x18\n" +
	" \x01(\x02R\x11speakerSimilarity\x12.\n" +
	"\x13segment_duration_ms\x18\v \x01(\x03R\x11segmentDurationMs\"\xd3\x01\n" +
	"\n" +
	"ClientMeta\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x01 \x01(\tR\tuserAgent\x12\x1f\n" +
	"\vsdk_version\x18\x02 \x01(\tR\n" +
	"sdkVersion\x12\x1e\n" +
	"\n" +
	"resolution\x18\x03 \x01(\tR\n" +
	"resolution\x12.\n" +
	"\x13timezone_offset_min\x18\x04 \x01(\x05R\x11timezoneOffsetMin\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\"T\n" +
	"\x12IngestEventRequest\x12>\n" +
	"\x05event\x18\x01 \x01(\v2(.argus.eventcollector.v1.ProctoringEventR\x05event\"h\n" +
	"\x13IngestEventResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x03R\bsequence\"q\n" +
	"\x12IngestBatchRequest\x12@\n" +
	"\x06events\x18\x01 \x03(\v2(.argus.eventcollector.v1.ProctoringEventR\x06events\x12\x19\n" +
	"\bbatch_id\x18\x02 \x01(\tR\abatchId\"\xb8\x01\n" +
	"\x13IngestBatchResponse\x12%\n" +
	"\x0eaccepted_count\x18\x01 \x01(\x05R\racceptedCount\x12%\n" +
	"\x0erejected_count\x18\x02 \x01(\x05R\rrejectedCount\x12,\n" +
	"\x12rejected_event_ids\x18\x03 \x03(\tR\x10rejectedEventIds\x12%\n" +
	"\x0ebatch_sequence\x18\x04 \x01(\x03R\rbatchSequence\"^\n" +
	"\tStreamAck\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\"\x89\x02\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x17\n" +
	"\aexam_id\x18\x03 \x01(\tR\x06examId\x12E\n" +
	"\x10client_timestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0fclientTimestamp\x12.\n" +
	"\x13current_focus_score\x18\x05 \x01(\x02R\x11currentFocusScore\x12'\n" +
	"\x0fviolation_count\x18\x06 \x01(\x05R\x0eviolationCount\"\xca\x01\n" +
	"\x11HeartbeatResponse\x12%\n" +
	"\x0esession_active\x18\x01 \x01(\bR\rsessionActive\x12E\n" +
	"\x10server_timestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0fserverTimestamp\x12G\n" +
	"\tdirective\x18\x03 \x01(\v2).argus.eventcollector.v1.SessionDirectiveR\tdirective\"\xaa\x01\n" +
	"\x10SessionDirective\x12M\n" +
	"\x0etelemetry_mode\x18\x01 \x01(\x0e2&.argus.eventcollector.v1.TelemetryModeR\rtelemetryMode\x12\x1c\n" +
	"\tterminate\x18\x02 \x01(\bR\tterminate\x12)\n" +
	"\x10terminate_reason\x18\x03 \x01(\tR\x0fterminateReason*\x9b\f\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eGAZE_DEVIATION\x10\x01\x12\x11\n" +
	"\rFACE_MISMATCH\x10\x02\x12\x15\n" +
	"\x11FACE_NOT_DETECTED\x10\x03\x12\x17\n" +
	"\x13FACE_SPOOF_DETECTED\x10\x04\x12\x14\n" +
	"\x10MULTIPLE_PERSONS\x10\x05\x12\x1d\n" +
	"\x19DYNAMIC_FACE_RECHECK_FAIL\x10\x06\x12\x15\n" +
	"\x11HEAD_POSE_ANOMALY\x10\a\x12\x19\n" +
	"\x15LIVENESS_CHECK_FAILED\x10\b\x12\x11\n" +
	"\rFACE_OCCLUDED\x10\t\x12\x12\n" +
	"\x0ePHONE_DETECTED\x10\n" +
	"\x12\x11\n" +
	"\rBOOK_DETECTED\x10\v\x12\x14\n" +
	"\x10EARBUDS_DETECTED\x10\f\x12\x1b\n" +
	"\x17UNKNOWN_OBJECT_DETECTED\x10\r\x12\x12\n" +
	"\x0eVOICE_ACTIVITY\x10\x14\x12\x11\n" +
	"\rAUDIO_ANOMALY\x10\x15\x12\x1c\n" +
	"\x18AUDIO_PERIPHERY_DETECTED\x10\x16\x12\x1a\n" +
	"\x16SMART_NOISE_CLASSIFIED\x10\x17\x12\x14\n" +
	"\x10WHISPER_DETECTED\x10\x18\x12\x1b\n" +
	"\x17SECOND_SPEAKER_DETECTED\x10\x19\x12\x1b\n" +
	"\x17AUDIO_PLAYBACK_DETECTED\x10\x1a\x12\x0e\n" +
	"\n" +
	"TAB_SWITCH\x10\x1e\x12\x16\n" +
	"\x12COPY_PASTE_ATTEMPT\x10\x1f\x12\x18\n" +
	"\x14PRINT_SCREEN_ATTEMPT\x10 \x12\x18\n" +
	"\x14CONTEXT_MENU_ATTEMPT\x10!\x12\x13\n" +
	"\x0fFULLSCREEN_EXIT\x10\"\x12\x1d\n" +
	"\x19EXTERNAL_DISPLAY_DETECTED\x10#\x12\x16\n" +
	"\x12VPN_PROXY_DETECTED\x10(\x12\x1d\n" +
	"\x19SUSPICIOUS_NETWORK_DEVICE\x10)\x12\x18\n" +
	"\x14EMOTION_STRESS_SPIKE\x102\x12\x17\n" +
	"\x13FOCUS_LOSS_DETECTED\x103\x12\x19\n" +
	"\x15BLINK_PATTERN_ANOMALY\x104\x12\x1b\n" +
	"\x17TYPING_DYNAMICS_ANOMALY\x10<\x12\x16\n" +
	"\x12HAND_CURSOR_DESYNC\x10=\x12\x1e\n" +
	"\x1aFORBIDDEN_PROCESS_DETECTED\x10>\x12\x1b\n" +
	"\x17HARDWARE_DEVICE_ANOMALY\x10?\x12\x1a\n" +
	"\x16REMOTE_ACCESS_DETECTED\x10@\x12\x18\n" +
	"\x14HARDWARE_ID_MISMATCH\x10A\x12\x1c\n" +
	"\x18VIRTUAL_MONITOR_DETECTED\x10B\x12\x1c\n" +
	"\x18VIRTUAL_MACHINE_DETECTED\x10C\x12\x1c\n" +
	"\x18SIDECAM_DEVICE_DISPLACED\x10F\x12\x1a\n" +
	"\x16SIDECAM_HANDS_OFF_DESK\x10G\x12\x1c\n" +
	"\x18SIDECAM_BATTERY_CRITICAL\x10H\x12\x1f\n" +
	"\x1bSIDECAM_STREAM_DISCONNECTED\x10I\x12\x1e\n" +
	"\x1aSIDECAM_CALIBRATION_FAILED\x10J\x12\x1c\n" +
	"\x18SIDECAM_THERMAL_THROTTLE\x10K\x12\x1c\n" +
	"\x18BACKEND_AI_FACE_MISMATCH\x10P\x12 \n" +
	"\x1cBACKEND_AI_SCREEN_REFLECTION\x10Q\x12\x1f\n" +
	"\x1bBACKEND_AI_MICRO_EXPRESSION\x10R\x12\x1c\n" +
	"\x18BACKEND_AI_HIDDEN_OBJECT\x10S\x12 \n" +
	"\x1cBACKEND_AI_DEEPFAKE_DETECTED\x10T\x12\x1a\n" +
	"\x16BACKEND_AI_VOICE_SYNTH\x10U\x12\x12\n" +
	"\x0eGAZE_TELEMETRY\x10d\x12\x13\n" +
	"\x0fMOUSE_TELEMETRY\x10e\x12\x16\n" +
	"\x12KEYBOARD_TELEMETRY\x10f\x12\x16\n" +
	"\x12FOCUS_SCORE_UPDATE\x10g\x12\x17\n" +
	"\x13HEAD_POSE_TELEMETRY\x10h\x12\x1c\n" +
	"\x18FACE_EMBEDDING_TELEMETRY\x10i\x12\x19\n" +
	"\x15AUDIO_LEVEL_TELEMETRY\x10j*I\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02\x12\f\n" +
	"\bCRITICAL\x10\x03*\x90\x01\n" +
	"\vEventSource\x12\x16\n" +
	"\x12SOURCE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06WEBCAM\x10\x01\x12\x0f\n" +
	"\vSIDE_CAMERA\x10\x02\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x03\x12\v\n" +
	"\aBROWSER\x10\x04\x12\x10\n" +
	"\fKERNEL_AGENT\x10\x05\x12\x11\n" +
	"\rNETWORK_PROBE\x10\x06\x12\x0e\n" +
	"\n" +
	"BACKEND_AI\x10\a*V\n" +
	"\rTelemetryMode\x12\x14\n" +
	"\x10TELEMETRY_NORMAL\x10\x00\x12\x17\n" +
	"\x13TELEMETRY_HIGH_FREQ\x10\x01\x12\x16\n" +
	"\x12TELEMETRY_LOW_FREQ\x10\x022\xb4\x03\n" +
	"\x15EventCollectorService\x12h\n" +
	"\vIngestEvent\x12+.argus.eventcollector.v1.IngestEventRequest\x1a,.argus.eventcollector.v1.IngestEventResponse\x12h\n" +
	"\vIngestBatch\x12+.argus.eventcollector.v1.IngestBatchRequest\x1a,.argus.eventcollector.v1.IngestBatchResponse\x12c\n" +
	"\fStreamEvents\x12+.argus.eventcollector.v1.IngestEventRequest\x1a\".argus.eventcollector.v1.StreamAck(\x010\x01\x12b\n" +
	"\tHeartbeat\x12).argus.eventcollector.v1.HeartbeatRequest\x1a*.argus.eventcollector.v1.HeartbeatResponseBCZAgithub.com/argus-ai/event-collector/api/proto/v1;eventcollectorv1b\x06proto3"

var (
	file_api_proto_v1_event_collector_proto_rawDescOnce sync.Once
	file_api_proto_v1_event_collector_proto_rawDescData []byte
)

func file_api_proto_v1_event_collector_proto_rawDescGZIP() []byte {
	file_api_proto_v1_event_collector_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_event_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_event_collector_proto_rawDesc), len(file_api_proto_v1_event_collector_proto_rawDesc)))
	})
	return file_api_proto_v1_event_collector_proto_rawDescData
}

var file_api_proto_v1_event_collector_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_proto_v1_event_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_api_proto_v1_event_collector_proto_goTypes = []any{
	(EventType)(0),                 // 0: argus.eventcollector.v1.EventType
	(Severity)(0),                  // 1: argus.eventcollector.v1.Severity
	(EventSource)(0),               // 2: argus.eventcollector.v1.EventSource
	(TelemetryMode)(0),             // 3: argus.eventcollector.v1.TelemetryMode
	(*ProctoringEvent)(nil),        // 4: argus.eventcollector.v1.ProctoringEvent
	(*GazeDeviationPayload)(nil),   // 5: argus.eventcollector.v1.GazeDeviationPayload
	(*FaceDetectionPayload)(nil),   // 6: argus.eventcollector.v1.FaceDetectionPayload
	(*ObjectDetectionPayload)(nil), // 7: argus.eventcollector.v1.ObjectDetectionPayload
	(*AudioPayload)(nil),           // 8: argus.eventcollector.v1.AudioPayload
	(*BrowserPayload)(nil),         // 9: argus.eventcollector.v1.BrowserPayload
	(*SystemPayload)(nil),          // 10: argus.eventcollector.v1.SystemPayload
	(*PsychometryPayload)(nil),     // 11: argus.eventcollector.v1.PsychometryPayload
	(*NetworkPayload)(nil),         // 12: argus.eventcollector.v1.NetworkPayload
	(*KernelPayload)(nil),          // 13: argus.eventcollector.v1.KernelPayload
	(*HeadPosePayload)(nil),        // 14: argus.eventcollector.v1.HeadPosePayload
	(*LivenessPayload)(nil),        // 15: argus.eventcollector.v1.LivenessPayload
	(*FaceEmbeddingPayload)(nil),   // 16: argus.eventcollector.v1.FaceEmbeddingPayload
	(*AudioAnalysisPayload)(nil),   // 17: argus.eventcollector.v1.AudioAnalysisPayload
	(*ClientMeta)(nil),             // 18: argus.eventcollector.v1.ClientMeta
	(*IngestEventRequest)(nil),     // 19: argus.eventcollector.v1.IngestEventRequest
	(*IngestEventResponse)(nil),    // 20: argus.eventcollector.v1.IngestEventResponse
	(*IngestBatchRequest)(nil),     // 21: argus.eventcollector.v1.IngestBatchRequest
	(*IngestBatchResponse)(nil),    // 22: argus.eventcollector.v1.IngestBatchResponse
	(*StreamAck)(nil),              // 23: argus.eventcollector.v1.StreamAck
	(*HeartbeatRequest)(nil),       // 24: argus.eventcollector.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 25: argus.eventcollector.v1.HeartbeatResponse
	(*SessionDirective)(nil),       // 26: argus.eventcollector.v1.SessionDirective
	(*timestamppb.Timestamp)(nil),  // 27: google.protobuf.Timestamp
}
var file_api_proto_v1_event_collector_proto_depIdxs = []int32{
	0,  // 0: argus.eventcollector.v1.ProctoringEvent.event_type:type_name -> argus.eventcollector.v1.EventType
	1,  // 1: argus.eventcollector.v1.ProctoringEvent.severity:type_name -> argus.eventcollector.v1.Severity
	2,  // 2: argus.eventcollector.v1.ProctoringEvent.source:type_name -> argus.eventcollector.v1.EventSource
	27, // 3: argus.eventcollector.v1.ProctoringEvent.server_timestamp:type_name -> google.protobuf.Timestamp
	27, // 4: argus.eventcollector.v1.ProctoringEvent.client_timestamp:type_name -> google.protobuf.Timestamp
	5,  // 5: argus.eventcollector.v1.ProctoringEvent.gaze_deviation:type_name -> argus.eventcollector.v1.GazeDeviationPayload
	6,  // 6: argus.eventcollector.v1.ProctoringEvent.face_detection:type_name -> argus.eventcollector.v1.FaceDetectionPayload
	7,  // 7: argus.eventcollector.v1.ProctoringEvent.object_detection:type_name -> argus.eventcollector.v1.ObjectDetectionPayload
	8,  // 8: argus.eventcollector.v1.ProctoringEvent.audio:type_name -> argus.eventcollector.v1.AudioPayload
	9,  // 9: argus.eventcollector.v1.ProctoringEvent.browser:type_name -> argus.eventcollector.v1.BrowserPayload
	10, // 10: argus.eventcollector.v1.ProctoringEvent.system:type_name -> argus.eventcollector.v1.SystemPayload
	11, // 11: argus.eventcollector.v1.ProctoringEvent.psychometry:type_name -> argus.eventcollector.v1.PsychometryPayload
	12, // 12: argus.eventcollector.v1.ProctoringEvent.network:type_name -> argus.eventcollector.v1.NetworkPayload
	13, // 13: argus.eventcollector.v1.ProctoringEvent.kernel:type_name -> argus.eventcollector.v1.KernelPayload
	14, // 14: argus.eventcollector.v1.ProctoringEvent.head_pose:type_name -> argus.eventcollector.v1.HeadPosePayload
	15, // 15: argus.eventcollector.v1.ProctoringEvent.liveness:type_name -> argus.eventcollector.v1.LivenessPayload
	17, // 16: argus.eventcollector.v1.ProctoringEvent.audio_analysis:type_name -> argus.eventcollector.v1.AudioAnalysisPayload
	16, // 17: argus.eventcollector.v1.ProctoringEvent.face_embedding:type_name -> argus.eventcollector.v1.FaceEmbeddingPayload
	18, // 18: argus.eventcollector.v1.ProctoringEvent.client_meta:type_name -> argus.eventcollector.v1.ClientMeta
	4,  // 19: argus.eventcollector.v1.IngestEventRequest.event:type_name -> argus.eventcollector.v1.ProctoringEvent
	4,  // 20: argus.eventcollector.v1.IngestBatchRequest.events:type_name -> argus.eventcollector.v1.ProctoringEvent
	27, // 21: argus.eventcollector.v1.HeartbeatRequest.client_timestamp:type_name -> google.protobuf.Timestamp
	27, // 22: argus.eventcollector.v1.HeartbeatResponse.server_timestamp:type_name -> google.protobuf.Timestamp
	26, // 23: argus.eventcollector.v1.HeartbeatResponse.directive:type_name -> argus.eventcollector.v1.SessionDirective
	3,  // 24: argus.eventcollector.v1.SessionDirective.telemetry_mode:type_name -> argus.eventcollector.v1.TelemetryMode
	19, // 25: argus.eventcollector.v1.EventCollectorService.IngestEvent:input_type -> argus.eventcollector.v1.IngestEventRequest
	21, // 26: argus.eventcollector.v1.EventCollectorService.IngestBatch:input_type -> argus.eventcollector.v1.IngestBatchRequest
	19, // 27: argus.eventcollector.v1.EventCollectorService.StreamEvents:input_type -> argus.eventcollector.v1.IngestEventRequest
	24, // 28: argus.eventcollector.v1.EventCollectorService.Heartbeat:input_type -> argus.eventcollector.v1.HeartbeatRequest
	20, // 29: argus.eventcollector.v1.EventCollectorService.IngestEvent:output_type -> argus.eventcollector.v1.IngestEventResponse
	22, // 30: argus.eventcollector.v1.EventCollectorService.IngestBatch:output_type -> argus.eventcollector.v1.IngestBatchResponse
	23, // 31: argus.eventcollector.v1.EventCollectorService.StreamEvents:output_type -> argus.eventcollector.v1.StreamAck
	25, // 32: argus.eventcollector.v1.EventCollectorService.Heartbeat:output_type -> argus.eventcollector.v1.HeartbeatResponse
	29, // [29:33] is the sub-list for method output_type
	25, // [25:29] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_api_proto_v1_event_collector_proto_init() }
func file_api_proto_v1_event_collector_proto_init() {
	if File_api_proto_v1_event_collector_proto != nil {
		return
	}
	file_api_proto_v1_event_collector_proto_msgTypes[0].OneofWrappers = []any{
		(*ProctoringEvent_GazeDeviation)(nil),
		(*ProctoringEvent_FaceDetection)(nil),
		(*ProctoringEvent_ObjectDetection)(nil),
		(*ProctoringEvent_Audio)(nil),
		(*ProctoringEvent_Browser)(nil),
		(*ProctoringEvent_System)(nil),
		(*ProctoringEvent_Psychometry)(nil),
		(*ProctoringEvent_Network)(nil),
		(*ProctoringEvent_Kernel)(nil),
		(*ProctoringEvent_HeadPose)(nil),
		(*ProctoringEvent_Liveness)(nil),
		(*ProctoringEvent_AudioAnalysis)(nil),
		(*ProctoringEvent_FaceEmbedding)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_event_collector_proto_rawDesc), len(file_api_proto_v1_event_collector_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_event_collector_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_event_collector_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_event_collector_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_event_collector_proto_msgTypes,
	}.Build()
	File_api_proto_v1_event_collector_proto = out.File
	file_api_proto_v1_event_collector_proto_goTypes = nil
	file_api_proto_v1_event_collector_proto_depIdxs = nil
}
