// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/proto/v1/inferencepb/inference.proto

package inferencepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferenceService_AnalyzeFrame_FullMethodName = "/argus.inference.v1.InferenceService/AnalyzeFrame"
	InferenceService_AnalyzeVideo_FullMethodName = "/argus.inference.v1.InferenceService/AnalyzeVideo"
)

// InferenceServiceClient is the client API for InferenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InferenceServiceClient interface {
	// AnalyzeFrame processes a single image frame and returns face detections,
	// object detections, and liveness verification results.
	AnalyzeFrame(ctx context.Context, in *AnalyzeFrameRequest, opts ...grpc.CallOption) (*AnalyzeFrameResponse, error)
	// AnalyzeVideo accepts a client-streamed video segment (WebM/MP4 chunks)
	// and returns frame-by-frame analysis with an aggregate fraud summary.
	// Used by the Worker for post-session deep scans.
	AnalyzeVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AnalyzeVideoChunk, AnalyzeVideoResponse], error)
}

type inferenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceServiceClient(cc grpc.ClientConnInterface) InferenceServiceClient {
	return &inferenceServiceClient{cc}
}

func (c *inferenceServiceClient) AnalyzeFrame(ctx context.Context, in *AnalyzeFrameRequest, opts ...grpc.CallOption) (*AnalyzeFrameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeFrameResponse)
	err := c.cc.Invoke(ctx, InferenceService_AnalyzeFrame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceClient) AnalyzeVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AnalyzeVideoChunk, AnalyzeVideoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InferenceService_ServiceDesc.Streams[0], InferenceService_AnalyzeVideo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AnalyzeVideoChunk, AnalyzeVideoResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceService_AnalyzeVideoClient = grpc.ClientStreamingClient[AnalyzeVideoChunk, AnalyzeVideoResponse]

// InferenceServiceServer is the server API for InferenceService service.
// All implementations must embed UnimplementedInferenceServiceServer
// for forward compatibility.
type InferenceServiceServer interface {
	// AnalyzeFrame processes a single image frame and returns face detections,
	// object detections, and liveness verification results.
	AnalyzeFrame(context.Context, *AnalyzeFrameRequest) (*AnalyzeFrameResponse, error)
	// AnalyzeVideo accepts a client-streamed video segment (WebM/MP4 chunks)
	// and returns frame-by-frame analysis with an aggregate fraud summary.
	// Used by the Worker for post-session deep scans.
	AnalyzeVideo(grpc.ClientStreamingServer[AnalyzeVideoChunk, AnalyzeVideoResponse]) error
	mustEmbedUnimplementedInferenceServiceServer()
}

// UnimplementedInferenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceServiceServer struct{}

func (UnimplementedInferenceServiceServer) AnalyzeFrame(context.Context, *AnalyzeFrameRequest) (*AnalyzeFrameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeFrame not implemented")
}
func (UnimplementedInferenceServiceServer) AnalyzeVideo(grpc.ClientStreamingServer[AnalyzeVideoChunk, AnalyzeVideoResponse]) error {
	return status.Error(codes.Unimplemented, "method AnalyzeVideo not implemented")
}
func (UnimplementedInferenceServiceServer) mustEmbedUnimplementedInferenceServiceServer() {}
func (UnimplementedInferenceServiceServer) testEmbeddedByValue()                          {}

// UnsafeInferenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceServiceServer will
// result in compilation errors.
type UnsafeInferenceServiceServer interface {
	mustEmbedUnimplementedInferenceServiceServer()
}

func RegisterInferenceServiceServer(s grpc.ServiceRegistrar, srv InferenceServiceServer) {
	// If the following call panics, it indicates UnimplementedInferenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferenceService_ServiceDesc, srv)
}

func _InferenceService_AnalyzeFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeFrameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).AnalyzeFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceService_AnalyzeFrame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).AnalyzeFrame(ctx, req.(*AnalyzeFrameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceService_AnalyzeVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InferenceServiceServer).AnalyzeVideo(&grpc.GenericServerStream[AnalyzeVideoChunk, AnalyzeVideoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceService_AnalyzeVideoServer = grpc.ClientStreamingServer[AnalyzeVideoChunk, AnalyzeVideoResponse]

// InferenceService_ServiceDesc is the grpc.ServiceDesc for InferenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "argus.inference.v1.InferenceService",
	HandlerType: (*InferenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeFrame",
			Handler:    _InferenceService_AnalyzeFrame_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AnalyzeVideo",
			Handler:       _InferenceService_AnalyzeVideo_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/v1/inferencepb/inference.proto",
}
