// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: api/proto/v1/inferencepb/inference.proto

package inferencepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeFrameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session context for correlation with proctoring events.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StudentId string `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	ExamId    string `protobuf:"bytes,3,opt,name=exam_id,json=examId,proto3" json:"exam_id,omitempty"`
	OrgId     string `protobuf:"bytes,4,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Raw image bytes (JPEG or PNG).
	FrameData []byte `protobuf:"bytes,5,opt,name=frame_data,json=frameData,proto3" json:"frame_data,omitempty"`
	// MIME type of the frame data ("image/jpeg" or "image/png").
	ContentType string `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Position in the session recording (seconds from session start).
	VideoTimestampSec float64 `protobuf:"fixed64,7,opt,name=video_timestamp_sec,json=videoTimestampSec,proto3" json:"video_timestamp_sec,omitempty"`
	// Enrolled ArcFace embedding used to compute identity similarity.
	ReferenceEmbedding []float32 `protobuf:"fixed32,8,rep,packed,name=reference_embedding,json=referenceEmbedding,proto3" json:"reference_embedding,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AnalyzeFrameRequest) Reset() {
	*x = AnalyzeFrameRequest{}
	mi := &file_api_proto_v1_inferencepb_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeFrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeFrameRequest) ProtoMessage() {}

func (x *AnalyzeFrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inferencepb_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeFrameRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeFrameRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inferencepb_inference_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeFrameRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AnalyzeFrameRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *AnalyzeFrameRequest) GetExamId() string {
	if x != nil {
		return x.ExamId
	}
	return ""
}

func (x *AnalyzeFrameRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *AnalyzeFrameRequest) GetFrameData() []byte {
	if x != nil {
		return x.FrameData
	}
	return nil
}

func (x *AnalyzeFrameRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *AnalyzeFrameRequest) GetVideoTimestampSec() float64 {
	if x != nil {
		return x.VideoTimestampSec
	}
	return 0
}

func (x *AnalyzeFrameRequest) GetReferenceEmbedding() []float32 {
	if x != nil {
		return x.ReferenceEmbedding
	}
	return nil
}

type AnalyzeFrameResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All faces detected in the frame.
	Faces []*FaceDetection `protobuf:"bytes,1,rep,name=faces,proto3" json:"faces,omitempty"`
	// All objects detected in the frame.
	Objects []*ObjectDetection `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
	// Liveness verification result for the primary face.
	Liveness *LivenessResult `protobuf:"bytes,3,opt,name=liveness,proto3" json:"liveness,omitempty"`
	// Server-side processing latency in milliseconds.
	ProcessingTimeMs float64 `protobuf:"fixed64,4,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AnalyzeFrameResponse) Reset() {
	*x = AnalyzeFrameResponse{}
	mi := &file_api_proto_v1_inferencepb_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeFrameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeFrameResponse) ProtoMessage() {}

func (x *AnalyzeFrameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inferencepb_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeFrameResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeFrameResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inferencepb_inference_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeFrameResponse) GetFaces() []*FaceDetection {
	if x != nil {
		return x.Faces
	}
	return nil
}

func (x *AnalyzeFrameResponse) GetObjects() []*ObjectDetection {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *AnalyzeFrameResponse) GetLiveness() *LivenessResult {
	if x != nil {
		return x.Liveness
	}
	return nil
}

func (x *AnalyzeFrameResponse) GetProcessingTimeMs() float64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

type AnalyzeVideoChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session context (only required on the first chunk).
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OrgId     string `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Raw video bytes (partial or complete segment).
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// MIME type of the video ("video/webm" or "video/mp4").
	ContentType string `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// True if this is the final chunk in the stream.
	IsLast        bool `protobuf:"varint,5,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeVideoChunk) Reset() {
	*x = AnalyzeVideoChunk{}
	mi := &file_api_proto_v1_inferencepb_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeVideoChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeVideoChunk) ProtoMessage() {}

func (x *AnalyzeVideoChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inferencepb_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeVideoChunk.ProtoReflect.Descriptor instead.
func (*AnalyzeVideoChunk) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inferencepb_inference_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeVideoChunk) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AnalyzeVideoChunk) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *AnalyzeVideoChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AnalyzeVideoChunk) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *AnalyzeVideoChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

type AnalyzeVideoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Per-frame analysis results (sampled at the configured frame rate).
	Frames []*FrameAnalysis `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"`
	// Aggregate summary across all analyzed frames.
	Summary *AnalysisSummary `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	// Total server-side processing time in milliseconds.
	TotalProcessingTimeMs float64 `protobuf:"fixed64,3,opt,name=total_processing_time_ms,json=totalProcessingTimeMs,proto3" json:"total_processing_time_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AnalyzeVideoResponse) Reset() {
	*x = AnalyzeVideoResponse{}
	mi := &file_api_proto_v1_inferencepb_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeVideoResponse) ProtoMessage() {}

func (x *AnalyzeVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inferencepb_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeVideoResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeVideoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inferencepb_inference_proto_rawDescGZIP(), []int{3}
}

func (x *AnalyzeVideoResponse) GetFrames() []*FrameAnalysis {
	if x != nil {
		return x.Frames
	}
	return nil
}

func (x *AnalyzeVideoResponse) GetSummary() *AnalysisSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *AnalyzeVideoResponse) GetTotalProcessingTimeMs() float64 {
	if x != nil {
		return x.TotalProcessingTimeMs
	}
	return 0
}

type FrameAnalysis struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp in seconds from the start of the video segment.
	TimestampSec  float64            `protobuf:"fixed64,1,opt,name=timestamp_sec,json=timestampSec,proto3" json:"timestamp_sec,omitempty"`
	Faces         []*FaceDetection   `protobuf:"bytes,2,rep,name=faces,proto3" json:"faces,omitempty"`
	Objects       []*ObjectDetection `protobuf:"bytes,3,rep,name=objects,proto3" json:"objects,omitempty"`
	Liveness      *LivenessResult    `protobuf:"bytes,4,opt,name=liveness,proto3" json:"liveness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameAnalysis) Reset() {
	*x = FrameAnalysis{}
	mi := &file_api_proto_v1_inferencepb_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameAnalysis) ProtoMessage() {}

func (x *FrameAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inferencepb_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameAnalysis.ProtoReflect.Descriptor instead.
func (*FrameAnalysis) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inferencepb_inference_proto_rawDescGZIP(), []int{4}
}

func (x *FrameAnalysis) GetTimestampSec() float64 {
	if x != nil {
		return x.TimestampSec
	}
	return 0
}

func (x *FrameAnalysis) GetFaces() []*FaceDetection {
	if x != nil {
		return x.Faces
	}
	return nil
}

func (x *FrameAnalysis) GetObjects() []*ObjectDetection {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *FrameAnalysis) GetLiveness() *LivenessResult {
	if x != nil {
		return x.Liveness
	}
	return nil
}

type FaceDetection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Detection confidence (0.0 - 1.0).
	Confidence float32 `protobuf:"fixed32,1,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Bounding box coordinates (normalized 0-1).
	BboxX float32 `protobuf:"fixed32,2,opt,name=bbox_x,json=bboxX,proto3" json:"bbox_x,omitempty"`
	BboxY float32 `protobuf:"fixed32,3,opt,name=bbox_y,json=bboxY,proto3" json:"bbox_y,omitempty"`
	BboxW float32 `protobuf:"fixed32,4,opt,name=bbox_w,json=bboxW,proto3" json:"bbox_w,omitempty"`
	BboxH float32 `protobuf:"fixed32,5,opt,name=bbox_h,json=bboxH,proto3" json:"bbox_h,omitempty"`
	// 512-dimensional ArcFace embedding vector.
	Embedding []float32 `protobuf:"fixed32,6,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	// Cosine similarity to the enrolled face (-1.0 if not computed).
	Similarity float32 `protobuf:"fixed32,7,opt,name=similarity,proto3" json:"similarity,omitempty"`
	// Anti-spoofing result.
	IsSpoof   bool   `protobuf:"varint,8,opt,name=is_spoof,json=isSpoof,proto3" json:"is_spoof,omitempty"`
	SpoofType string `protobuf:"bytes,9,opt,name=spoof_type,json=spoofType,proto3" json:"spoof_type,omitempty"` // "photo" | "video" | "mask" | "deepfake" | ""
	// Head pose angles in degrees.
	HeadYaw       float32 `protobuf:"fixed32,10,opt,name=head_yaw,json=headYaw,proto3" json:"head_yaw,omitempty"`
	HeadPitch     float32 `protobuf:"fixed32,11,opt,name=head_pitch,json=headPitch,proto3" json:"head_pitch,omitempty"`
	HeadRoll      float32 `protobuf:"fixed32,12,opt,name=head_roll,json=headRoll,proto3" json:"head_roll,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaceDetection) Reset() {
	*x = FaceDetection{}
	mi := &file_api_proto_v1_inferencepb_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaceDetection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceDetection) ProtoMessage() {}

func (x *FaceDetection) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inferencepb_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceDetection.ProtoReflect.Descriptor instead.
func (*FaceDetection) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inferencepb_inference_proto_rawDescGZIP(), []int{5}
}

func (x *FaceDetection) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *FaceDetection) GetBboxX() float32 {
	if x != nil {
		return x.BboxX
	}
	return 0
}

func (x *FaceDetection) GetBboxY() float32 {
	if x != nil {
		return x.BboxY
	}
	return 0
}

func (x *FaceDetection) GetBboxW() float32 {
	if x != nil {
		return x.BboxW
	}
	return 0
}

func (x *FaceDetection) GetBboxH() float32 {
	if x != nil {
		return x.BboxH
	}
	return 0
}

func (x *FaceDetection) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *FaceDetection) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

func (x *FaceDetection) GetIsSpoof() bool {
	if x != nil {
		return x.IsSpoof
	}
	return false
}

func (x *FaceDetection) GetSpoofType() string {
	if x != nil {
		return x.SpoofType
	}
	return ""
}

func (x *FaceDetection) GetHeadYaw() float32 {
	if x != nil {
		return x.HeadYaw
	}
	return 0
}

func (x *FaceDetection) GetHeadPitch() float32 {
	if x != nil {
		return x.HeadPitch
	}
	return 0
}

func (x *FaceDetection) GetHeadRoll() float32 {
	if x != nil {
		return x.HeadRoll
	}
	return 0
}

type ObjectDetection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Object class label.
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"` // "phone" | "book" | "earbuds" | "screen_reflection" | "person"
	// Detection confidence (0.0 - 1.0).
	Confidence float32 `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Bounding box coordinates (normalized 0-1).
	BboxX         float32 `protobuf:"fixed32,3,opt,name=bbox_x,json=bboxX,proto3" json:"bbox_x,omitempty"`
	BboxY         float32 `protobuf:"fixed32,4,opt,name=bbox_y,json=bboxY,proto3" json:"bbox_y,omitempty"`
	BboxW         float32 `protobuf:"fixed32,5,opt,name=bbox_w,json=bboxW,proto3" json:"bbox_w,omitempty"`
	BboxH         float32 `protobuf:"fixed32,6,opt,name=bbox_h,json=bboxH,proto3" json:"bbox_h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectDetection) Reset() {
	*x = ObjectDetection{}
	mi := &file_api_proto_v1_inferencepb_inference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectDetection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectDetection) ProtoMessage() {}

func (x *ObjectDetection) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inferencepb_inference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectDetection.ProtoReflect.Descriptor instead.
func (*ObjectDetection) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inferencepb_inference_proto_rawDescGZIP(), []int{6}
}

func (x *ObjectDetection) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *ObjectDetection) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ObjectDetection) GetBboxX() float32 {
	if x != nil {
		return x.BboxX
	}
	return 0
}

func (x *ObjectDetection) GetBboxY() float32 {
	if x != nil {
		return x.BboxY
	}
	return 0
}

func (x *ObjectDetection) GetBboxW() float32 {
	if x != nil {
		return x.BboxW
	}
	return 0
}

func (x *ObjectDetection) GetBboxH() float32 {
	if x != nil {
		return x.BboxH
	}
	return 0
}

type LivenessResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Liveness score (0.0 = definite spoof, 1.0 = definitely live).
	Score float32 `protobuf:"fixed32,1,opt,name=score,proto3" json:"score,omitempty"`
	// Binary liveness decision.
	IsLive bool `protobuf:"varint,2,opt,name=is_live,json=isLive,proto3" json:"is_live,omitempty"`
	// Method used for liveness detection.
	Method        string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"` // "texture" | "blink" | "depth"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LivenessResult) Reset() {
	*x = LivenessResult{}
	mi := &file_api_proto_v1_inferencepb_inference_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivenessResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivenessResult) ProtoMessage() {}

func (x *LivenessResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inferencepb_inference_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivenessResult.ProtoReflect.Descriptor instead.
func (*LivenessResult) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inferencepb_inference_proto_rawDescGZIP(), []int{7}
}

func (x *LivenessResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *LivenessResult) GetIsLive() bool {
	if x != nil {
		return x.IsLive
	}
	return false
}

func (x *LivenessResult) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type AnalysisSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of frames analyzed in the video.
	TotalFramesAnalyzed int32 `protobuf:"varint,1,opt,name=total_frames_analyzed,json=totalFramesAnalyzed,proto3" json:"total_frames_analyzed,omitempty"`
	// Count of frames where fraud indicators were detected.
	FraudFrames int32 `protobuf:"varint,2,opt,name=fraud_frames,json=fraudFrames,proto3" json:"fraud_frames,omitempty"`
	// Count of frames where the face did not match the enrolled identity.
	FaceMismatchFrames int32 `protobuf:"varint,3,opt,name=face_mismatch_frames,json=faceMismatchFrames,proto3" json:"face_mismatch_frames,omitempty"`
	// Count of frames where spoofing was detected.
	SpoofFrames int32 `protobuf:"varint,4,opt,name=spoof_frames,json=spoofFrames,proto3" json:"spoof_frames,omitempty"`
	// Count of frames where prohibited objects were detected.
	ObjectDetectionFrames int32 `protobuf:"varint,5,opt,name=object_detection_frames,json=objectDetectionFrames,proto3" json:"object_detection_frames,omitempty"`
	// Maximum fraud confidence across all frames (0.0 - 1.0).
	MaxFraudConfidence float32 `protobuf:"fixed32,6,opt,name=max_fraud_confidence,json=maxFraudConfidence,proto3" json:"max_fraud_confidence,omitempty"`
	// Aggregate verdict for the entire video segment.
	Verdict       string `protobuf:"bytes,7,opt,name=verdict,proto3" json:"verdict,omitempty"` // "clean" | "suspicious" | "fraud"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisSummary) Reset() {
	*x = AnalysisSummary{}
	mi := &file_api_proto_v1_inferencepb_inference_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisSummary) ProtoMessage() {}

func (x *AnalysisSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inferencepb_inference_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisSummary.ProtoReflect.Descriptor instead.
func (*AnalysisSummary) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inferencepb_inference_proto_rawDescGZIP(), []int{8}
}

func (x *AnalysisSummary) GetTotalFramesAnalyzed() int32 {
	if x != nil {
		return x.TotalFramesAnalyzed
	}
	return 0
}

func (x *AnalysisSummary) GetFraudFrames() int32 {
	if x != nil {
		return x.FraudFrames
	}
	return 0
}

func (x *AnalysisSummary) GetFaceMismatchFrames() int32 {
	if x != nil {
		return x.FaceMismatchFrames
	}
	return 0
}

func (x *AnalysisSummary) GetSpoofFrames() int32 {
	if x != nil {
		return x.SpoofFrames
	}
	return 0
}

func (x *AnalysisSummary) GetObjectDetectionFrames() int32 {
	if x != nil {
		return x.ObjectDetectionFrames
	}
	return 0
}

func (x *AnalysisSummary) GetMaxFraudConfidence() float32 {
	if x != nil {
		return x.MaxFraudConfidence
	}
	return 0
}

func (x *AnalysisSummary) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

var File_api_proto_v1_inferencepb_inference_proto protoreflect.FileDescriptor

const file_api_proto_v1_inferencepb_inference_proto_rawDesc = "" +
	"\n" +
	"(api/proto/v1/inferencepb/inference.proto\x12\x12argus.inference.v1\"\xa6\x02\n" +
	"\x13AnalyzeFrameRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x17\n" +
	"\aexam_id\x18\x03 \x01(\tR\x06examId\x12\x15\n" +
	"\x06org_id\x18\x04 \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"frame_data\x18\x05 \x01(\fR\tframeData\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12.\n" +
	"\x13video_timestamp_sec\x18\a \x01(\x01R\x11videoTimestampSec\x12/\n" +
	"\x13reference_embedding\x18\b \x03(\x02R\x12referenceEmbedding\"\xfc\x01\n" +
	"\x14AnalyzeFrameResponse\x127\n" +
	"\x05faces\x18\x01 \x03(\v2!.argus.inference.v1.FaceDetectionR\x05faces\x12=\n" +
	"\aobjects\x18\x02 \x03(\v2#.argus.inference.v1.ObjectDetectionR\aobjects\x12>\n" +
	"\bliveness\x18\x03 \x01(\v2\".argus.inference.v1.LivenessResultR\bliveness\x12,\n" +
	"\x12processing_time_ms\x18\x04 \x01(\x01R\x10processingTimeMs\"\x99\x01\n" +
	"\x11AnalyzeVideoChunk\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x17\n" +
	"\ais_last\x18\x05 \x01(\bR\x06isLast\"\xc9\x01\n" +
	"\x14AnalyzeVideoResponse\x129\n" +
	"\x06frames\x18\x01 \x03(\v2!.argus.inference.v1.FrameAnalysisR\x06frames\x12=\n" +
	"\asummary\x18\x02 \x01(\v2#.argus.inference.v1.AnalysisSummaryR\asummary\x127\n" +
	"\x18total_processing_time_ms\x18\x03 \x01(\x01R\x15totalProcessingTimeMs\"\xec\x01\n" +
	"\rFrameAnalysis\x12#\n" +
	"\rtimestamp_sec\x18\x01 \x01(\x01R\ftimestampSec\x127\n" +
	"\x05faces\x18\x02 \x03(\v2!.argus.inference.v1.FaceDetectionR\x05faces\x12=\n" +
	"\aobjects\x18\x03 \x03(\v2#.argus.inference.v1.ObjectDetectionR\aobjects\x12>\n" +
	"\bliveness\x18\x04 \x01(\v2\".argus.inference.v1.LivenessResultR\bliveness\"\xda\x02\n" +
	"\rFaceDetection\x12\x1e\n" +
	"\n" +
	"confidence\x18\x01 \x01(\x02R\n" +
	"confidence\x12\x15\n" +
	"\x06bbox_x\x18\x02 \x01(\x02R\x05bboxX\x12\x15\n" +
	"\x06bbox_y\x18\x03 \x01(\x02R\x05bboxY\x12\x15\n" +
	"\x06bbox_w\x18\x04 \x01(\x02R\x05bboxW\x12\x15\n" +
	"\x06bbox_h\x18\x05 \x01(\x02R\x05bboxH\x12\x1c\n" +
	"\tembedding\x18\x06 \x03(\x02R\tembedding\x12\x1e\n" +
	"\n" +
	"similarity\x18\a \x01(\x02R\n" +
	"similarity\x12\x19\n" +
	"\bis_spoof\x18\b \x01(\bR\aisSpoof\x12\x1d\n" +
	"\n" +
	"spoof_type\x18\t \x01(\tR\tspoofType\x12\x19\n" +
	"\bhead_yaw\x18\n" +
	" \x01(\x02R\aheadYaw\x12\x1d\n" +
	"\n" +
	"head_pitch\x18\v \x01(\x02R\theadPitch\x12\x1b\n" +
	"\thead_roll\x18\f \x01(\x02R\bheadRoll\"\xae\x01\n" +
	"\x0fObjectDetection\x12\x1f\n" +
	"\vobject_type\x18\x01 \x01(\tR\n" +
	"objectType\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x15\n" +
	"\x06bbox_x\x18\x03 \x01(\x02R\x05bboxX\x12\x15\n" +
	"\x06bbox_y\x18\x04 \x01(\x02R\x05bboxY\x12\x15\n" +
	"\x06bbox_w\x18\x05 \x01(\x02R\x05bboxW\x12\x15\n" +
	"\x06bbox_h\x18\x06 \x01(\x02R\x05bboxH\"W\n" +
	"\x0eLivenessResult\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x02R\x05score\x12\x17\n" +
	"\ais_live\x18\x02 \x01(\bR\x06isLive\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\"\xc1\x02\n" +
	"\x0fAnalysisSummary\x122\n" +
	"\x15total_frames_analyzed\x18\x01 \x01(\x05R\x13totalFramesAnalyzed\x12!\n" +
	"\ffraud_frames\x18\x02 \x01(\x05R\vfraudFrames\x120\n" +
	"\x14face_mismatch_frames\x18\x03 \x01(\x05R\x12faceMismatchFrames\x12!\n" +
	"\fspoof_frames\x18\x04 \x01(\x05R\vspoofFrames\x126\n" +
	"\x17object_detection_frames\x18\x05 \x01(\x05R\x15objectDetectionFrames\x120\n" +
	"\x14max_fraud_confidence\x18\x06 \x01(\x02R\x12maxFraudConfidence\x12\x18\n" +
	"\averdict\x18\a \x01(\tR\averdict2\xd8\x01\n" +
	"\x10InferenceService\x12a\n" +
	"\fAnalyzeFrame\x12'.argus.inference.v1.AnalyzeFrameRequest\x1a(.argus.inference.v1.AnalyzeFrameResponse\x12a\n" +
	"\fAnalyzeVideo\x12%.argus.inference.v1.AnalyzeVideoChunk\x1a(.argus.inference.v1.AnalyzeVideoResponse(\x01B>Z<github.com/argus-ai/event-collector/api/proto/v1/inferencepbb\x06proto3"

var (
	file_api_proto_v1_inferencepb_inference_proto_rawDescOnce sync.Once
	file_api_proto_v1_inferencepb_inference_proto_rawDescData []byte
)

func file_api_proto_v1_inferencepb_inference_proto_rawDescGZIP() []byte {
	file_api_proto_v1_inferencepb_inference_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_inferencepb_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_inferencepb_inference_proto_rawDesc), len(file_api_proto_v1_inferencepb_inference_proto_rawDesc)))
	})
	return file_api_proto_v1_inferencepb_inference_proto_rawDescData
}

var file_api_proto_v1_inferencepb_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_v1_inferencepb_inference_proto_goTypes = []any{
	(*AnalyzeFrameRequest)(nil),  // 0: argus.inference.v1.AnalyzeFrameRequest
	(*AnalyzeFrameResponse)(nil), // 1: argus.inference.v1.AnalyzeFrameResponse
	(*AnalyzeVideoChunk)(nil),    // 2: argus.inference.v1.AnalyzeVideoChunk
	(*AnalyzeVideoResponse)(nil), // 3: argus.inference.v1.AnalyzeVideoResponse
	(*FrameAnalysis)(nil),        // 4: argus.inference.v1.FrameAnalysis
	(*FaceDetection)(nil),        // 5: argus.inference.v1.FaceDetection
	(*ObjectDetection)(nil),      // 6: argus.inference.v1.ObjectDetection
	(*LivenessResult)(nil),       // 7: argus.inference.v1.LivenessResult
	(*AnalysisSummary)(nil),      // 8: argus.inference.v1.AnalysisSummary
}
var file_api_proto_v1_inferencepb_inference_proto_depIdxs = []int32{
	5,  // 0: argus.inference.v1.AnalyzeFrameResponse.faces:type_name -> argus.inference.v1.FaceDetection
	6,  // 1: argus.inference.v1.AnalyzeFrameResponse.objects:type_name -> argus.inference.v1.ObjectDetection
	7,  // 2: argus.inference.v1.AnalyzeFrameResponse.liveness:type_name -> argus.inference.v1.LivenessResult
	4,  // 3: argus.inference.v1.AnalyzeVideoResponse.frames:type_name -> argus.inference.v1.FrameAnalysis
	8,  // 4: argus.inference.v1.AnalyzeVideoResponse.summary:type_name -> argus.inference.v1.AnalysisSummary
	5,  // 5: argus.inference.v1.FrameAnalysis.faces:type_name -> argus.inference.v1.FaceDetection
	6,  // 6: argus.inference.v1.FrameAnalysis.objects:type_name -> argus.inference.v1.ObjectDetection
	7,  // 7: argus.inference.v1.FrameAnalysis.liveness:type_name -> argus.inference.v1.LivenessResult
	0,  // 8: argus.inference.v1.InferenceService.AnalyzeFrame:input_type -> argus.inference.v1.AnalyzeFrameRequest
	2,  // 9: argus.inference.v1.InferenceService.AnalyzeVideo:input_type -> argus.inference.v1.AnalyzeVideoChunk
	1,  // 10: argus.inference.v1.InferenceService.AnalyzeFrame:output_type -> argus.inference.v1.AnalyzeFrameResponse
	3,  // 11: argus.inference.v1.InferenceService.AnalyzeVideo:output_type -> argus.inference.v1.AnalyzeVideoResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_v1_inferencepb_inference_proto_init() }
func file_api_proto_v1_inferencepb_inference_proto_init() {
	if File_api_proto_v1_inferencepb_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_inferencepb_inference_proto_rawDesc), len(file_api_proto_v1_inferencepb_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_inferencepb_inference_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_inferencepb_inference_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_inferencepb_inference_proto_msgTypes,
	}.Build()
	File_api_proto_v1_inferencepb_inference_proto = out.File
	file_api_proto_v1_inferencepb_inference_proto_goTypes = nil
	file_api_proto_v1_inferencepb_inference_proto_depIdxs = nil
}
